pingcap/tiproxy

.coverage.out
.github/workflow_calls/common.yml
.github/workflows/build.yml
.github/workflows/test.yml
.gitignore
Makefile

Issue Number: ref #23 
Problem Summary: add basic github CI
Tests 
```release-note
None
```

*: add CI pipe line

---

.gitignore
Makefile
cmd/weirctl/config.go
cmd/weirctl/main.go
cmd/weirctl/namespace.go
cmd/weirctl/util.go
conf/namespace/test_namespace.yaml
conf/weirproxy.yaml
pkg/config/proxy.go
pkg/config/proxy_test.go
pkg/manager/config/manager.go
pkg/manager/config/manager_test.go
pkg/manager/config/namespace.go
pkg/manager/config/proxy.go
pkg/manager/config/proxy_test.go
pkg/manager/config/utils.go
pkg/proxy/proxy.go
pkg/server/api/api.go
pkg/server/api/config.go
pkg/server/api/debug.go
pkg/server/api/namespace.go
pkg/server/server.go
pkg/util/errors/werror.go
pkg/util/errors/werror_test.go

Issue Number: ref #57
Problem Summary: Dynamic config `keep alive` and `max connections` for proxy server.
1. In short, added background service for config manager to poll online config regularlly/watch etcd event. It will then be applied to the running server.
2. API return value minor improvement. Added `/api/admin/config/proxy` for online proxy config.
3. Configs have `yaml, toml, json` all struct tags
4. `errors.Wrap(f)` will return nil for nil error
5. Makefile minor improvement
Tests 
```
./bin/weirproxy ...
echo '{"max_connections": 0}' | ./bin/weirctl config proxy
zero connection error
echo '{"max_connections": 1}' | ./bin/weirctl config proxy
start two mysql client, and one of them will be rejected by …
```

config: dynamic proxy config

---

conf/namespace/default.yaml
conf/namespace/test_namespace.yaml
conf/weirproxy.yaml
pkg/config/namespace.go
pkg/config/proxy.go

Issue Number: close #46 
Problem Summary: As title.
Tests 
```release-note
None
```

config: consistent marshal name

---

pkg/manager/router/router_test.go

`TestConnBalanced` is unstable because I forgot to call `redirectFinish` before checking metrics.
Add `redirectFinish`. I tested it several times and it's OK now.
Tests 
```release-note
None
```

router: fix unstable test `TestConnBalanced`

---

.github/workflows/common.yml
.github/workflows/main.yml
Makefile

Problem Summary: Another CI improvement.
1. `build` job can be replaced by `lint` job
2. adapt the "best" from the master, improve cache hit rate
3. remove `make build`, add `make dev`
Tests 
```release-note
None
```

*: better workflow

---

Makefile

Output UT coverage.
Output UT coverage.
Tests 
```release-note
None
```

*: output coverage stats to the makefile

---

.github/workflows/common.yml
Makefile

Problem Summary: As title, really needs some trial and error..
Tests 
```release-note
None
```

*: fix CI cache

---

lib/util/security/tls.go
pkg/manager/cert/cert_info.go
pkg/manager/cert/manager.go
pkg/manager/cert/manager_test.go

Support rotating CA for all kinds of certs.
- Set `InsecureSkipVerify + VerifyPeerCertificate` for the client TLS config.
- Set `GetConfigForClient` for the server TLS config.
Tests 
```release-note
None
```

manager: rotate ca

---

.dockerignore
docker/Dockerfile

Problem Summary: Use two-stage build to give a clean and smaller prod environment.
Tests 
```release-note
None
```

*: improve dockerfile

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/mock_proxy_test.go

Problem Summary: Similar to #117
What is changed and how it works: Only require TLS if `require-backend-tls = true`
Tests 
```release-note
None
```

*: redirect without TLS

---

pkg/proxy/backend/backend_conn_mgr.go

Problem Summary: add one more logging message at debug level.
Tests 
```release-note
None
```

*: add log for mysql error

---

docker/Dockerfile
lib/cli/main.go
pkg/server/server.go

Problem Summary: Specify all kinds of timeout for HTTP server and clients, especially `IdleTimeout`, which may cause infinite goroutines under some circumstances.
Tests 
```release-note
None
```

*: timeout for cli and server

---

pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet

Add a goroutine count panel to inspect the goroutine count.
Add a goroutine count panel.
Tests 
Check the grafana panel.
Something's wrong with github and I cannot upload the screenshot.
```release-note
None
```

metrics: add goroutine panel

---

pkg/proxy/backend/backend_conn_mgr.go

Signed-off-by: disksing <i@disksing.com>
If the router is recently created, the backend list may not been fetched yet, so need to retry.
Tests 
```release-note
None
```

Route retry

---

pkg/metrics/alertmanager/tiproxy.rules.yml

Problem Summary: Ref [monitoring commit](https://github.com/pingcap/monitoring/compare/master...xhebox:monitoring:master). Need alert rules for monitoring images.
Tests 
```release-note
None
```

metrics: add alertmanager

---

.github/workflows/common.yml

Problem Summary: CI tests done, debug dispatch works now. Revert back the `failure()`.
Tests 
```release-note
None
```

*: fix CI debug

---

Makefile
docker/Dockerfile

Problem Summary: Fix docker build problems after #177 .
Tests 
```release-note
None
```

*: fix docker build problem

---

Makefile
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: ref #192 
as title
Tests 
```release-note
None
```

test: use  require.Eventually instead of sleep

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go

To adapt to serverless tier, the timeout parameters are not suitable.
Adjust the parameters. Later, we need to make them configurable.
Tests 
```release-note
None
```

backend: adjust timeout parameters

---

pkg/proxy/backend/backend_conn_mgr.go

Problem Summary: Set keepalive for backend connections.
Tests 
```release-note
None
```

proxy: set keepalive for backend connections

---

lib/config/proxy.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/proxy_test.go
pkg/proxy/net/tls.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

Issue Number: ref #229
Problem Summary: As title
Tests 
```release-note
None
```

router: set keepalive according to status

---

go.mod
go.sum
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Problem Summary: Generic list, eliminating needs of type casting.
Tests 
```release-note
None
```

router: generic list

---

lib/util/security/cert.go
lib/util/security/cert_test.go
lib/util/security/tls.go

Issue Number: ref #264
Tests 
```release-note
None
```

security: set minimum version to TLS11

---

pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: ref #233
Problem Summary: Cleanup.
Tests 
```release-note
None
```

backend: use atomic.Pointer for *signalRedirect

---

.github/workflows/release.yaml

Tests 
```release-note
None
```

workflow: fix typo

---

pkg/manager/config/config.go

Issue Number: ref #286
Problem Summary: Print config every update
Tests 
```release-note
None
```

config: log every change

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor.go
pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/cmd_processor_query.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/backend/metrics.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/net/mysql.go

Tests 
```release-note
None
```

proxy: use pnet.Command

---

.goreleaser.yaml

Tests 
```release-note
None
```

*: fix goreleaser build

---

docker/Dockerfile

Tests 
```release-note
None
```

fix: remove https in Dockerfile

---

docker/Dockerfile

Tests 
```release-note
None
```

fix: remove mirrot test

---

Makefile
cmd/tiproxyctl/main.go

Issue Number: close #340
Problem Summary: Use versioninfo for ctl.
Tests 
```release-note
None
```

ctl: use versioninfo

---

Makefile

Issue Number: close #343
Problem Summary: add `make clean` to delete existed files.
Tests 
```release-note
None
```

make: add clean target

---

README.md

Add future plans and the blog link for reference.
Add future plans and the blog link for reference.
Tests 
```release-note
None
```

readme: add future plans and blog link

---

pkg/proxy/backend/authenticator.go

fix duplicated import path
Tests 
```release-note
None
```

backend: fix duplicated import

---

CHANGELOG.md
README.md

- No changelog
- Readme is outdated
- Add change log for v0.2.0
- Update readme to refer to the official doc
Tests 
```release-note
None
```

*: add changelog and update readme

---

pkg/manager/config/config_test.go

Issue Number: close #468
The test is still unstable, because the WRITE event may trigger 1 or 2 reloading. We must judge by the exact reloading times.
Judge the OS type and expect different reloading times.
Tests 
```release-note
None
```

config: make `TestFilePath` stable

---

pkg/metrics/alertmanager/tiproxy.rules.yml

Issue Number: close #480 
No alert rules yet.
Add alert rules
Tests 
```release-note
- Add alert rules
```

metrics: add alert rules

---

CHANGELOG.md

update changelog to v1.0.0
update changelog to v1.0.0
Tests 
```release-note
None
```

*: update changelog to v1.0.0

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/mock_test.go

Issue Number: close #540 
Support memory-based balance.
- Add a new factor `FactorMemory`.
Tests 
```release-note
- Support memory-based balance
```

factor: support memory-based balance

---

pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go

Issue Number: close #522 
Reading from MetricsReader is not in a push way anymore, it's in a pull way. We don't need `Subscribe`.
- Remove subscribe-related code in MetricsReader
Tests 
```release-note
None
```

metricsreader: remove subscribe functions for MetricsReader

---

pkg/balance/observer/backend_observer_test.go

Issue Number: close #564 
The test case is unstable because if the machine is very slow, the health check result doesn't contain any backends.
Check the query result of the map.
Tests 
```release-note
None
```

metricsreader: fix TestLocal

---

CHANGELOG.md

Update changelog to v1.1.0
Update changelog to v1.1.0
Tests 
```release-note
None
```

*: update changelog to v1.1.0

---

pkg/util/http/http.go

Issue Number: close https://github.com/pingcap/tiproxy/issues/602
What is changed and how it works: add some comment
Tests 
```release-note
None
```

http: add comment for explaining the new http cli design and usage

---

CHANGELOG.md

Add change log
Add change log
Tests 
```release-note
None
```

*: add change log for v1.2.0

---

go.mod
go.sum
pkg/proxy/backend/authenticator.go
pkg/proxy/net/compress.go
pkg/proxy/net/packetio.go

Issue Number: close #708 
`github.com/pingcap/tidb` depends on too many packages, which frequently causes dependency conflicts.
Remove all dependencies of `github.com/pingcap/tidb`.
Tests 
```release-note
None
```

*: remove dependency of module `github.com/pingcap/tidb`

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/factor_status.go
pkg/balance/factor/factor_status_test.go

Issue Number: ref #768 
Sometimes TiDB is unbalanced but it's hard to troubleshoot. Adding debug log will help.
Add some debug logs.
Tests 
Only debug logs are added.
```release-note
- Add debug log for balancing factors.
```

balance: add debug log for updating balance count

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go

Issue Number: close #806 
When routing and setting config concurrently, the `FactorBasedBalance.factors` is read and written concurrently, leading a data race.
Add a lock in the `FactorBasedBalance`.
Tests 
```release-note
- Fix data race when routing and setting config concurrently.
```

balance: fix potential data race when setting config by adding a lock

---

go.mod
go.sum
pkg/manager/meter/meter.go
pkg/manager/meter/meter_test.go

Issue Number: close #857
Update metering sdk
update metering sdk and the API
Tests 
```release-note
None
```

meter: update metering sdk
