pingcap/tiproxy

cmd/weirctl/main.go
cmd/weirproxy/main.go
pkg/util/cmd/cmd.go

Problem Summary: To reduce the risk of GA, the old encoder is brought back as the default.
What is changed and how it works: `StackTrace` by zap is multiline, this is not compatible with `tidb` format.
Tests 
```release-note
None
```

*: add pingcap/log encoder as the default encoder

---

cmd/weirctl/namespace.go
pkg/config/file.go
pkg/config/namespace.go
pkg/config/namespace_test.go
pkg/manager/config/namespace.go
pkg/server/api/config.go
pkg/server/api/debug.go
pkg/server/api/namespace.go
pkg/server/server.go

Issue Number: ref #11
Problem Summary: Reduce assumption on what format the server will return or store.
What is changed and how it works:  The server will process json only now. The cli is resposible to convert it from yaml to json or vice versa.
Tests 
```
./bin/weirctl namespace list
./bin/weirctl namespace get default
./bin/weirctl namespace put
```
```release-note
None
```

server: use json for API and internal storage

---

pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router.go

Issue Number: close #58
- The status port cannot stand for the real status of the SQL server.
- Lack of tests
- Also fetch `/topology/tidb/ip:port/ttl` to filter tombstone backends
- Dial both the status port and the MySQL protocol port to check the health
- Add tests
I also proposed 2 enhancements for TiDB graceful shutdown: https://github.com/pingcap/tidb/issues/37471
TODO:
- Expose some configurations, such as health check interval, just like HAProxy https://github.com/pingcap/TiProxy/issues/60
- Split BackendStatus to a separate file
- Add TLS options to the HTTP status and etcd client connections
Tests 
Scale out and scale in the TiDB cluster during running sysbench. …

router: refine BackendObserver and add tests

---

pkg/util/cmd/encoder.go

Problem Summary: I don't know how it is produced. `len(xx) >= 0` is expected, thus the judgement should be true forever. Anyway, this is a try.
What is changed and how it works: 
1. `EncodeEntry` will not free the buffer anymore, it is left to zap logger, based on https://github.com/uber-go/zap/blob/4a895a245ab794e3ae965783843a9fbc793083bc/zapcore/core.go#L95-L100
2. `StackTrace` by zap is multiline, this is not compatible with `tidb` format.
Tests 
```release-note
None
```

util: try to fix panic

---

.dockerignore
.gitignore
Makefile
docker/Dockerfile
docker/apk-fastest-mirror.sh
go.mod

Issue Number: ref #69
Problem Summary: Need a docker image.
What is changed and how it works: Add `make docker` for building an image.
Tests 
```
make docker
```
```release-note
None
```

docker: add docker support

---

pkg/manager/namespace/manager.go
pkg/manager/router/router.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #71
These things may happen concurrently:
- The Router sends a redirection signal to the BackendConnMgr
- The BackendConnMgr closes due to client or backend disconnection.
There are 2 problems:
- `BackendConnMgr.Redirect()` reports a panic because it assumes that it's not closed.
- `Router.OnConnClosed()` cannot find the connection by the backend address, because the address passed in by `BackendConnMgr` is the old one, not the new one (just sent by `BackendConnMgr.Redirect()`).
- Fix the problems by getting the latest address from `GetRedirectingAddr()`.
- Make `BackendConnMgr` notify the `Router` asynchronously to:
- Reduce the latency of session migration. The notification may wait for Router locks. The client …

backend, router: fix errors when closing and redirecting concurrently

---

pkg/proxy/backend/backend_conn_mgr.go

Some test cases are unstable, such as `TestNormalRedirect`(https://github.com/pingcap/TiProxy/runs/8181135325?check_suite_focus=true) and `TestRedirectFail`.
Reason:
This is a bug introduced by https://github.com/pingcap/TiProxy/pull/72. It doesn't only happen in testing.
Since `BackendConnManager.processSignals` also handles `mgr.redirectResCh` now, this may happen:
- The process signal goroutine is executing `notifyRedirectResult()` and calls `OnRedirectSucceed()`.
- The router sees that the redirection succeeds and sends another redirection signal immediately.
- The process signal goroutine is just returning from `notifyRedirectResult()` but does not go to the `select-case` yet.
- `BackendConnManager.Redirect` is a non-blocking function but the …

backend: fix the bug that the redirection signal may be discarded

---

pkg/manager/router/router.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #73 
- ~~When the sysbench closes, the rebalancer frequently migrates sessions because the connections are unbalanced again and again after closing too many connections.~~
- Lack of tests.
- ~~Add a minimal interval to the redirection to avoid migrating too frequently.~~
- Add a minimal interval for redirection failure to avoid unnecessary retrials. That is, after a connection fails to redirect (maybe because it contains local temporary tables), it won't be redirected again in 3 seconds.
- Add the unhealthy empty backend back to the router when a connection fails to redirect and cannot find the original backend. This avoids wild connections.
- When the balancer searches for a connection to redirect, skip the …

router: add tests for router

---

.github/workflows/build.yml
.gitignore
Makefile
lib/config/namespace_test.go
lib/config/proxy_test.go

Issue Number: ref #76
Problem Summary: go commands is module based. Need to manually run for each module.
1. run tests for `/lib`
2. merge coverage profiles
Tests 
Ensured tests under `/lib` are passed.
```release-note
None
```

*: fix multi module test

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/proxy.go

Issue Number: ref #8 
Problem Summary: Now only `router` have `logutil` logger left.
Tests 
```release-note
None
```

*: remove logutil in proxy

---

go.mod
pkg/manager/namespace/manager.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/net/net_err.go
pkg/proxy/net/packetio.go
pkg/proxy/proxy.go

Issue Number: ref #8
- Remove logutil for router
- Some unimportant errors are printed. E.g. when the client closes unexpectedly, there are always 2 logs:
```
[2022/09/15 16:02:55.908 +08:00] [INFO] [main.proxy] [client_conn.go:81] ["process message fails"] connID=39 [remoteAddr=127.0.0.1:50444] [error="failed to read the connection: read tcp 127.0.0.1:6000->127.0.0.1:50444: read: connection reset by peer"]
[2022/09/15 16:02:55.927 +08:00] [INFO] [main.proxy] [proxy.go:140] ["connection closed"] connID=28 [error="failed to close client connection:\n\tfailed to close the connection:\n\ttls: failed to send closeNotify alert (but connection was closed anyway): write tcp 127.0.0.1:6000->127.0.0.1:50436: write: broken pipe"]
```
The error `tls: failed to send closeNotify alert …

router, proxy: refine logs of router and backend

---

pkg/proxy/net/capability.go
pkg/proxy/net/capability_test.go

Problem Summary: The motivation is that I want to print capability difference between server and proxy in a human readable format.  I'll modify all capability flags in the package to this type later. And maybe cherry pick the change to `tidb/parser`.
What is changed and how it works: A new capability flag type with `fmt.Sringer` and `TextMarshaler`.
Tests 
```release-note
None
```

proxy/net: human readable capability flag

---

lib/util/errors/merror.go
lib/util/errors/merror_test.go
pkg/manager/namespace/manager.go
pkg/proxy/proxy.go

Problem Summary: Open a client conenction. Close `tiproxy` without interrupting the connection, tiproxy will hang.
1. `MError` should not have `Unwrap` method. It is unsuitable to unwrap multiple errors into one specific error. But unwrapping to itself may cause infinite recursion, because some functions will unwrap forever if he can.
2. While `router` and `backendObserver` does not inherit the cancel context, we can close `namespaces`, which will try to close routers.
3. No need to `ProxyServer.wg.Wait()`. We already waited at `Close()`.
Tests 
```
./bin/tiproxy
mycli -u root -P 6000 // in another terminal
type ctrl+c for tiproxy and see it hangs or not
```
Please refer …

*: fix hang bug

---

pkg/manager/config/manager.go
pkg/manager/config/proxy_test.go

Problem Summary: Watch rev is computed after firing the go routine. That said another go routine may race and change `e.kv.Rev()` such that `e.watch()` is not watching the correct revision.
What is changed and how it works: Compute it outside the go routine.
Tests 
```release-note
None
```

*: compute rev before firing go routines

---

pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go

Problem Summary: Another logging improvement. `EOF` is normal and should be seen as error.
Tests 
```release-note
None
```

proxy/client: do not print error on EOF

---

lib/util/errors/merror.go
lib/util/errors/merror_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/proxy.go
pkg/server/server.go

Problem Summary: `errors.Collect` will filter nil errors automatically, saving you from the tedious `if err != nil { errs = append(errs, ..) }`. 
Tests 
```release-note
None
```

*: filter nil errors

---

pkg/manager/logger/manager_test.go

The test case `TestUpdateCfg` is unstable: the backup files are not removed immediately.
It's probably caused by asynchronously removing files. I added some delay to the check. 
I added a loop to run it 100 times, it always succeeds no matter before or after this PR.
Tests 
```release-note
None
```

logger: fix case `TestUpdateCfg`

---

cmd/tiproxyctl/main.go
go.mod
lib/cli/main.go
lib/cli/util.go

Issue Number: ref #69
Problem Summary: The main purpose is to enable passing TLSConfig programatically, which makes it embeddable in other applications like operator.
1. `GetRootCmd` now accepts `tls.Config`, the main purpose
2. Silent usage on errors. Only manually print usages on argument mismatch or so.
3. Support passing tls set from cli, and automatically request with or without SSL
4. Fix handling of `res.StatusCode != http.StatusOK`
5. Handle cases where server with TLS but clients request plain http and vice versa
Tests 
```
Just enable server with or with TLS and test
One special case is to test !200 cases. Start tiproxy without PD, and you will hit `service not ready` in the first 5 seconds or so 100%. …
```

*: ctl TLS refine

---

.golangci.yaml
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_backend_test.go

In this case:
- The client handshakes with TiDB with default db `A`
- The client `use B` and `drop database A`
- The proxy migrates the session
Previously, the migration with fail because `B` is dropped.
Update the current DB in the authenticator to the one in the session states.
Tests 
```release-note
None
```

backend: update db in the handshake

---

.github/workflows/main.yml

Problem Summary: Forgot remove `build` target from cache job.
Tests 
```release-note
None
```

*: fix master CI cache

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/authenticator_test.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/packetio_mysql.go

Issue Number: ref: #109 
- With default settings, the client always fails to connect now. The proxy doesn't support CLIENT_SSL by default (auto_tls is false) but the backend does. When the proxy forwards the initial handshake from the backend to the client (without updating the capability), the client thinks the proxy supports CLIENT_SSL and then fails.
- Given that we're going to support HTAP splitting, the proxy needs to handshake with the client first.
- Handshake with the client first; write the handshake response to the backend by itself. Thus it's more natural to change the capability.
- Always send an invalid auth method to the backend the first time to require another switch request. Otherwise, if the proxy forwards a correct auth …

backend: handshake with client first

---

conf/proxy.yaml
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/proxy.go

Issue Number: ref #14 
Problem Summary: Support proxy-protocol for redirection.
Tests 
`tiup playground --db.config xx` where xx is a file of following contents:
```
[security]
auto-tls = true
[proxy-protocol]
networks = "*"
timeout = 10
```
Enable proxy protocol on tiproxy and start.
Connect to tiproxy by `mycli -u root -P 6000`.
`curl -X "POST" -L http://127.0.0.1:3080/api/debug/redirect` will see `redirecti connection succeeds` in tiproxy log.
```release-note
None
```

*: support proxy protocol on reconnection

---

cmd/tiproxy/main.go
lib/config/proxy.go
pkg/server/server.go

Issue Number: ref #69
Problem Summary: Support a cluster of tiproxy nodes.
What is changed and how it works: Add five new cmd flags.
Tests 
```
n1: 3080,3081,6000
n2: 4080,4081,7000
rm -rf work && ./bin/tiproxy --node_name=n1 --bootstrap_clusters "n2=127.0.0.1:4081" --config conf/proxy.yaml
rm -rf work2 && ./bin/tiproxy --node_name=n2 --bootstrap_clusters "n1=127.0.0.1:3081" --config conf2/proxy.yaml
After bootstraping
stop one node and restart it by ./bin/tiproxy  --config conf/proxy.yaml
```
```release-note
None
```

*: support clustering

---

lib/util/security/tls.go
pkg/manager/cert/manager.go
pkg/manager/cert/manager_test.go
pkg/manager/namespace/manager.go
pkg/manager/namespace/namespace.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/proxy/proxy.go
pkg/server/server.go

The proxy is supposed to be always online, so it should reload certs automatically, rather than reloading it by restarting the proxy.
- All the TLS configs are created and managed by CertManager.
- The CertManager reloads certs periodically.
- For auto-created certs, the CertManager recreates it periodically.
- The peer certs are not reloaded. The ETCD should reload it when it expires.
Currently, the CertManager reloads certificates periodically. Some alternatives:
- Check expiration time by reading the `NotAfter` field of the certs, but the rotation may not respect the expiration time.
- Check the modification time of the cert files periodically. If it changes, load it.
- When the operator replaces a cert, it …

manager: auto reload certs

---

lib/util/security/tls.go
lib/util/security/tls_test.go
pkg/manager/cert/manager_test.go

Problem Summary: pass rsa key size
Tests 
```release-note
None
```

*: pass rsa key size correctly

---

pkg/manager/router/backend_observer.go

Problem Summary: With `grpc.WithBlock()`, etcd client will exit if it fails to dial to PD. It is inconvenient sometimes:
1. start tiproxy first, playground second, and found tiproxy exited due to non-functional PD
2. on dev tier env, it is hard to ensure tiproxy will start immediately after PD. The time took by dev tier to start a tidb cluster is so long that k8s will crash tiproxy for at least 3 times, resulting into a very long backoff time.
What is changed and how it works: Remove that option.
Tests 
```release-note
None
```

router: do not fail if tiproxy can not connect PD in the first try

---

conf/namespace/test.yaml
conf/proxy.yaml
lib/config/namespace.go
lib/config/namespace_test.go
pkg/manager/namespace/manager.go
pkg/manager/namespace/namespace.go
pkg/manager/router/backend_observer.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/client/client_conn.go

Issue Number: ref #15
Problem Summary: Minimal effort to support multi-namespace routing by user. Also fixed broken static routing. It is initially coded for hackathon, but mergeable anyway.
It also reveals  some problems:
1. The abstraction `client -> backend -> auth` is a little bit redundant, or too ideal: we need to pass options back and forth. In fact, we only need one class to handle connection with seperated files for readability.
2. It can not be well tested with the current `mockProxy`: `mp` will construct a fixed backend with `connectionID = 0, proxy = false, require-backend-tls = false` and also `namespaceManager = nil` now.
We probably will add more and more options. Yet `clientConn` and `proxyServer` is not tested. Need something …

*: fix static backends & support route by user

---

lib/cli/config.go
lib/cli/namespace.go

Problem Summary: Use empty string to indicate stdin. Also use `cmd.InOrStdin` for `config set` as `namespace put`.
Tests 
```release-note
None
```

*: fix cli stdin

---

lib/util/cmd/encoder.go
lib/util/cmd/encoder_test.go

Issue Number: ref #8, `pingcap/log` section
Problem Summary: I made some mistakes when porting the encoder of `pingcap/log`. This PR should hopefully fix these issues.
1. Correctly escape characters, but not all characters as `pingcap/log`. The requirements are: first, double quotes if needed; second, one message one line, no wrapping.
2. Also escape `AppendReflected` and `AddString`, it is missed in my previous PR.
3. `AppendByteString` will encode to hex automatically. This does not violate the RFC. It actually makes more sense. In tikv, `[]byte` are mostly `keys`, which will be encoded into a human readable format. But that is not true in go or other components. Just convert all `[]byte` to hex. If you need …

*: fix newtidb encoder

---

cmd/tiproxy/main.go
lib/util/cmd/encoder.go
lib/util/cmd/encoder_test.go
lib/util/cmd/logger.go

Issue Number: ref #8
Problem Summary: Apply the new encoder.
1. Remove `pingcap/log` and the old encoder
2. Fix lint since #92 is too old that it is merged without linting.
3. Also escape tab character
4. Print escaped characters as `%04x` instead of `%4x`, i.e. fill with extra 0 instead of spaces.
5. Apply json and console encoder, which is removed in #88 and #99
Tests 
```
/bin/tiproxy should now use the new encoder
/bin/tiproxy --log_encoder json should out put json logs
```
```release-note
None
```

*: replace old encoder with new encoder

---

lib/util/errors/error.go
lib/util/errors/error_test.go
lib/util/errors/werror.go
lib/util/errors/werror_test.go
pkg/proxy/net/packetio.go

Problem Summary: There are two problems.
1. `p.wrap` is an error intended to wrap other errors, it should be appended to the error list of `pnet.Conn.Close()`.
2.  Change how `errors.Wrap` handles nil.
This fixes `[1.667360865291243e+09] [error] [main.proxy] [close connection fails] [connID=0] [remoteAddr="[::1]:51379"] [error="failed to close client connection:\n\tfailed to close the connection:\n\tthis is an error from client"]`.
Tests 
```release-note
None
```

*: handle more nil error cases

---

lib/util/cmd/logger.go

Problem Summary: Since we switched to manual creation of `zapcore.Core`, we lost some default configuration that is present in `zap.NewProductionLogger`, causing the new encode behave differently with the old log format.
1. correct time format
2. all upper case level
3. add `xxx.go:xxx`, i.e. caller information
Tests 
```release-note
None
```

*: fix log format

---

pkg/manager/cert/cert_info.go
pkg/proxy/backend/authenticator.go

Problem Summary: If server enables TLS, but we don't have certs to complete TLS handshake, there is a panic.
1. check `backendTLSConfig`
2. check `GetClientCertificate`
Tests 
```release-note
None
```

*: fix TLS cases

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/net/mysql.go

Issue Number: ref #127
Problem Summary: Minimal effort to support switch auth request when it is change user command. A little bit ugly.
Tests 
```
tiup --db.binpath ./tidb-server
./bin/tiproxy
mvn "-Dcom.mysql.jdbc.testsuite.url=jdbc:mysql://127.0.0.1:6000/test?user=root&password=&useSSL=false&useServerPrepStmts=true" '-Dtest=ConnectionRegressionTest#testBug19354014' test
```
```release-note
None
```

*: change user

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/util.go

Problem Summary: The fake salt does not have any usage. But client will still send the computed passwords with the fake salt in the response. In cases of non-TLS, all-zero salt will let client send a fixed auth string(sha1 three times with fixed input), which is highly insecure. Thus we should still send random salt instead.
Tests 
```release-note
None
```

*: add back salt

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/proxy.go
pkg/server/server.go

Signed-off-by: disksing <i@disksing.com>
To make it possible for a custom handshakeHandler to work without using a NamespaceManager.
Tests 
```release-note
None
```

proxy: remove NamespaceManager from HandshakeHandler interface

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go

change method `GetNamespace` to `GetRouter` so that custom handler can work without construct a `namespace.Namespace` struct.
Tests 
```release-note
None
```

backend: update handshakeHandler interface

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go

Signed-off-by: disksing <i@disksing.com>
Add context parameter for methods of responseHandler.
Move client address to context.
Later we can put more extra data in context.
Tests 
```release-note
None
```

backend: add context to pass parameters need by handler

---

cmd/tiproxy/main.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go
pkg/sctx/context.go
pkg/server/server.go

Issue Number: ref #136
Problem Summary: With authenticator being a `kvmap`, we can now support passing custom handler through `server.Context`.
Tests 
```release-note
None
```

server: support custom handler for Server

---

go.mod
go.sum
pkg/server/server.go

Problem Summary: To prevent too frequent API requests.
Tests 
```
while true; do
echo "$(date)"
i=0
while [ "${i}" -lt "110" ]; do
curl -Ls 127.0.0.1:3080/api/metrics > /dev/null
i=$((i+1))
done
curl -Ls 127.0.0.1:3080/api/metrics | head -1 || true
done
```
```release-note
None
```

server: default rate limit

---

pkg/server/server.go

Problem Summary: It is limiting `debug/pprof` to output metrics more than 30s.
Tests 
```release-note
None
```

*: remove write timeout

---

pkg/manager/router/router.go

Issue Number: ref #136
Problem Summary: Add new API as requested by @disksing 
Tests 
```release-note
None
```

router: add ConnCount

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go

Issue Number: ref #136 
Problem Summary: Change as requested, making `OnConnClose` aware of the completion of handshake.
Tests 
```release-note
None
```

backend: closed before/after handshake

---

go.mod
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go

Issue Number: ref #136
Problem Summary: `OnHandshake` will be invoked every time retrying connect or after the handshake.
Tests 
```release-note
None
```

backend: add OnHandshake

---

conf/proxy.yaml
lib/config/proxy.go
lib/config/proxy_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

Tests 
```release-note
None
```

server, backend: graceful shutdown

---

lib/util/security/cert.go
lib/util/security/cert_test.go

Issue Number: close #162
Problem Summary: Bug introduced by #146. TLS config for server is wrong if ca is not configured but certs.
What is changed and how it works: Added some unit tests to prevent regression.
Tests 
```release-note
None
```

security: fix server cert config

---

pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/authenticator_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/client/client_conn.go

Problem Summary: Another refactor to clean the code. `getBackendIO` is added to do namespace routing. Now it is done in `HandshakeHandler` by returning the correct router. So it is completely fine to remove `getBackendIO` now.
1. Split `ScoreBasedRouter` into a separate file.
2. Add `StaticRouter` for tests.
3. Add `ConnEventReceiver` interface as parts of `Router`
4. `getBackendIO` is moved into `handshakeFirstTime`
5. `handshakeFirstTime` is now a method of `BackendConnMgr` due to dependency problems.(handler is stored in the manager, not the authenticator)
6. Replace `github.com/pingcap/tidb/util.WaitGroupWrapper` with `github.com/pingcap/TiProxy/lib/util/waitgroup.WaitGroup`
7. …

backend: remove getBackendIO

---

conf/proxy.toml
lib/util/security/cert.go
lib/util/security/cert_test.go
lib/util/security/tls.go
lib/util/security/tls_test.go
pkg/manager/cert/manager.go
pkg/manager/cert/manager_test.go

Issue Number: ref #136 
Problem Summary: Serverless tier will provide CA now, which results into rejections to all clients without providing certs. This can be solved by not-specifying CA, or the new semantic of `TLSConfig`:
For a server TLS config, if ca is specified and `skip-ca==true`, server will not **require clients to provide certs**, but **recommend/request clients to provide certs if any**.
1. new semantic for server TLS
2. make `createTempTLS` private, expose `CreateTLSCertificates` to remove `AutoTLS`
3. remove `autoCertInterval`, which is replaced by refactored `certInfo.expire`
4. refactored cert manager tests to be simpler and cover more about rotation(improve coverage by 0.3%). Rotation(CA and certs) are covered by `TestRotate`. …

proxy: optional server-side verification

---

cmd/tiproxy/main.go
conf/proxy.toml
lib/config/proxy.go
lib/config/proxy_test.go
lib/util/security/tls.go

Issue Number: ref #161 
Problem Summary: Update default config values. This will enable to write less code in tidb-operator and dedicated tier.
What is changed:
1. default values for all config options.
2. tiproxy does not need a config file to start anymore.
3. Remove useless `rsa-key-size` in the security section.
Tests 
```
rm conf/proxy.toml
./bin/tiproxy
```
```release-note
None
```

lib/config: reasonable default config values

---

lib/util/security/cert.go

Issue Number: ref #161
Problem Summary: Missing in go1.16, causing tidb-operator fails to build.
Tests 
```release-note
None
```

*: avoid using official atomic.Int64

---

Makefile
cmd/tiproxy/main.go
cmd/tiproxyctl/main.go

Issue Number: ref #161 
Problem Summary: Requested by @lobshunter , version flags are added.
Tests 
```
./bin/tiproxy[ctl] [-v|--version]
```
```release-note
None
```

cmd: add version

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/proxy.go

Issue Number: close #175
Track traffic for each client (frontend) connection.
- Track traffic for `PacketIO`
- Add `ClientIO` as a member to `BackendConnMgr` to make track easier
- Add `InBytes()` and `OutBytes` for `ConnContext`
Tests 
```release-note
None
```

backend, net: track traffic for each client connection

---

pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/backend_selector.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go

Issue Number: close #179
Currently, when the backend fetcher returns an empty backend list, the proxy keeps retrying for 5 seconds.
However, the serverless tier may encounter some problems that can't be recovered immediately. In this case, the fetcher can return an error, indicating that the proxy doesn't need to retry.
- Add a return value of `error` type for `BackendFetcher.GetBackendList()`
- Add the return value for `Observer`, `BackendEventReceiver`, `BackendSelector`, and so on
- Stop retrying connecting if the error is not nil
Note that https://github.com/pingcap/TiProxy/issues/180 will be fixed in another PR.
Tests  …

router, backend: stop retrying connecting to backends if the fetcher fails

---

lib/cli/health.go
lib/cli/main.go
pkg/server/api/api.go
pkg/server/api/debug.go
pkg/server/api/http.go
pkg/server/server.go

Issue Number: ref #161 
Problem Summary: Depends on #191 , a better API for health checking. Also fixes for dockerfile. Also add `tiproxyctl health`.
Well-tested with the new tidb-operator PR.
Tests 
```release-note
None
```

api: add /api/debug/health

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/tls.go

Issue Number: close #195
On the serverless tier, when the client is idle for 5 minutes, the backend will quit. But the TiProxy doesn't know the backend quits because it's still reading the client. Then, the serverless tier thinks the connection is still alive and then wakes up a new TiDB instance.
So, TiProxy should always detect the backend and disconnect the client when the backend quits.
- Add a ticker on `BackendConnMgr` to check the backend periodically in the background goroutine
- Wrap the `PacketIO.conn` with a buffer and add `PacketIO.IsPeerActive()`
- Update the parameters of `NewBackendConnMgr` to make them configurable in the tests
- Fix `checkConnClosed4Proxy`. It never worked before because `ts.mp.err` is not checked
Tests …

backend, net: close the client connection when the backend is down

---

lib/config/health.go

Problem Summary: Embedding this struct into k8s types needs json tag.
Tests 
```release-note
None
```

config: add json tag

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/net/packetio.go

Signed-off-by: disksing <i@disksing.com>
set tls state in conn context, so later we can use `show session status` to check tls state.
Tests 
```release-note
None
```

backend: set tls state in conncontext

---

pkg/proxy/backend/backend_conn_mgr_test.go

https://github.com/pingcap/TiProxy/pull/201 tried to make the test faster but there's a misunderstanding here:
I want to prove that the status of `closeStatus` is always `statusNotifyClose` and will never change to `statusClosing` or `statusClosed`, so I waited for 300ms.
If it's changed to `require.Eventually`, it will definitely return on the first try.
Revert the code.
Tests 
```release-note
None
```

backend: revert PR 201 because to make the test accurate

---

lib/config/health.go
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go
pkg/server/api/debug.go

Issue Number: close #202
The operator or some other tools can fetch the checksum to know the version of the config.
Add the get checksum API for ConfigManager and HTTP.
Tests 
```release-note
None
```

config, api: add API for getting the config checksum 

---

lib/config/namespace.go
pkg/manager/namespace/manager.go
pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_fetcher_test.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Issue Number: close #205
The serverless tier doesn't need health check, because the standby tidb might be unhealthy.
- Add a member `Enable` to `config.HealthCheck`.
- Move `router.HealthCheckConfig` to `config.HealthCheck` and rename some members.
- Add a parameter `*config.HealthCheck` to `NewScoreBasedRouter()`.
TODO:
- Add `config.HealthCheck` to the configuration file. Currently, it's still using the default value.
- The `config.HealthCheck` parameter of `ScoreBasedRouter` and `PDFetcher` is duplicated and should be refined.
- Unit tests
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality release …

config, router: add health check switch

---

lib/config/namespace.go
pkg/manager/namespace/manager.go
pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Issue Number: close #207
- Close the router may cause deadlock: `router.Close()` holds `router.lock` and waits for `observer` to finish; `observer.observe()` calls `router.OnBackendChanged()`, which waits for `router.lock`.
- If `HealthCheck.Interval==0`, even if `HealthCheck.Enable==false`, there is no interval for calling `backendFetcher`, which exhausts lots of resources.
- Remove the locks for `StartScoreBasedRouter()` and `Close()`. The lock intends to protect `router.observer` and `router.cancelFunc` but they are not very necessary.
- Add a `HealthCheck.Check()` when creating `ScoreBasedRouter` and `PDFetcher`.
Tests  …

router, config: fix deadlock during closing the router

---

pkg/metrics/balance.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/session.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/metrics.go

Issue Number: close #210
Getting backend is problematic on the serverless tier. We need more logs to help investigating.
- Add error logs when getting backend fails; add warn logs when getting backend too slow
- Add duration metrics for getting backends
Tests 
```
[2023/02/06 15:20:54.085 +08:00] [ERROR] [main.proxy.conn.be] [backend/backend_conn_mgr.go:245] [get backend failed] [connID=0] [remoteAddr=127.0.0.1:62995] [duration=15.000037552s] [last_err="no instances to route"]
```
```
tiproxy_session_get_backend_duration_millis_bucket{le="0.001"} 0
tiproxy_session_get_backend_duration_millis_bucket{le="0.002"} 0
tiproxy_session_get_backend_duration_millis_bucket{le="0.004"} 0
tiproxy_session_get_backend_duration_millis_bucket{le="0.008"} …
```

backend, metrics: add logs and metrics for getting a backend

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/net/packetio_options.go
pkg/proxy/net/proxy.go
pkg/proxy/net/proxy_test.go

Issue Number: close #213
Problem Summary: Should unwrap `originAddr` first.
Tests 
```release-note
fix proxy-protocol not working
```

proxy: fix proxy-protocol under originAddr

---

pkg/proxy/backend/authenticator.go

node client cannot connect to server
test code 
```
var mysql = require('mysql');
var connection = mysql.createConnection({
host: '127.0.0.1',
port: 3306,
user: 'root',
password: '123456',
database: 'test',
});
connection.connect(function(err) {
if (err) {
throw err
}
connection.query('SELECT DATABASE();', function(err, rows) {
if (err) {
throw err
}
console.log(rows[0]['DATABASE()']);
connection.end()
});
})
```
the cause is that the client does not set capability flags correctly and the connection is terminated by tidb.
- always set ClientPluginAuth when connecting backend
- if client does not set ClientPluginAuth, log a warning
Tests  …

backend: always set ClientPluginAuth

---

pkg/proxy/backend/authenticator.go

If the client disables SSL, the proxy added CLIENT_SSL and passed it to the HandshakeHandler.
We don't need it anymore, because the CLIENT_SSL is added if backendConfig is configured.
Do not add CLIENT_SSL for the client response.
Tests 
```release-note
None
```

backend: do not add CLIENT_SSL for HandshakeHandler

---

pkg/proxy/backend/authenticator.go

Some drivers don't set ClientSSL in the second packet, but the HandshakeHandler wants the real capability.
Use the first capability for HandshakeHandler.
Tests 
```release-note
None
```

backend: add ssl to packet for HandshakeHandler

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_options.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/proxy_test.go
pkg/proxy/net/tls.go

Issue Number: ref https://github.com/pingcap/TiProxy/issues/229
To make set timeout / keep alive concurrently with forwarding messages / TLS handshake, the `mgr.backendIO` and `PacketIO.conn` must be concurrency safe.
- Make `mgr.backendIO` atomic
- Add RWMutex to `PacketIO.conn`
Tests 
```release-note
None
```

backend, net: make connection concurrency safe

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/error.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/client/client_conn.go

Issue Number: close #235
Gateway needs to know whether the client is disconnected normally or not.
Add QuitSource() to ConnContext. There are multiple sources.
Tests 
```release-note
None
```

backend: add quit source to ConnContext

---

.github/workflows/main.yml
lib/config/proxy.go
pkg/proxy/keepalive/keepalive.go
pkg/proxy/keepalive/keepalive_default.go
pkg/proxy/keepalive/keepalive_unix.go
pkg/proxy/keepalive/timeout_darwin.go
pkg/proxy/keepalive/timeout_default.go
pkg/proxy/keepalive/timeout_linux.go
pkg/proxy/keepalive/timeout_windows.go
pkg/proxy/net/packetio_test.go

Issue Number: ref #229
Problem Summary: When `ACK` not arrived in time, the connection will abort.
Tests 
```release-note
None
```

keepalive: RT timeout parameters

---

pkg/manager/namespace/manager.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go

Problem Summary: Instead of keep a map of `id <-> conn`, we could store additional router data, e.g. pointer to the list element, into `conn` directly.
1. Split `NewScoreBasedRouter` into two functions, another one is `Init`. It is to cleanup initialization in `router_test.go`. Gateway may need to adapt it.
2. Add `SetValue` and `Value`. It is used to store `Elemet[*connWrapper]`. We can locate the list element instantly.
Tests 
```release-note
None
```

router: remove connMap

---

lib/util/security/cert.go
lib/util/security/cert_test.go
pkg/manager/cert/manager.go
pkg/manager/cert/manager_test.go

Issue Number: close #243
Currently, the certs are reloaded when it's almost expired. However, if the user wants Bring Your Own Key, he should not care when the certs will expire.
- Remove `Cert.expire` and always reload the certs.
- For auto certs, recreate it in advance.
Tests 
```release-note
None
```

manager: remove expiration judgement and reload certs periodically

---

lib/config/proxy.go

Now that we have TCP timeout, we can make keep alive parameters less aggressive, because it only works when the client is idle.
Besides, 30s is too long for a backend to respond. The client cannot wait for 30s.
- Adjust healthy keep alive to 75s and timeout to 15s
- Adjust unhealthy keep alive to 15s and timeout to 5s
Tests 
```release-note
None
```

config: adjust keep alive parameters and add comments

---

Makefile
pkg/proxy/backend/authenticator.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_options.go
pkg/proxy/net/proxy.go
pkg/proxy/proxyprotocol/definition.go
pkg/proxy/proxyprotocol/error.go
pkg/proxy/proxyprotocol/proxy.go
pkg/proxy/proxyprotocol/proxy_test.go
pkg/testkit/main.go

Issue Number: ref #245
Problem Summary: Need to support proxy protocol for HTTP, too. Another point is that, epoll refactor will need a much simpler `PacketIO` and `backend` structure. So we seperate the package.
1. move `testPipe, testTCP` into `pkg/testkit`
2. seperate proxy protocol
3. add `var _ proxyprotocol.AddressWrapper = &originAddr{}`
Tests 
```release-note
None
```

proxy: move proxyprotocol as a seperate package

---

.github/workflows/main.yml
Makefile
pkg/proxy/backend/metrics.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/command.go
pkg/proxy/net/const.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_mysql.go

Issue Number: ref #248
Problem Summary: The current backend must convert from `*PacketIO` oriented to `[]byte/MysqlPacket` oriented. Command processor or authenticator should not read from the connection actively. To do this, we should provide a set of helpers that deals with packets, instead of `*PacketIO`.
1. This packet completes `mysql.ComXXX` definition. The next one will provide more helpers.
2. fix post merge CI.
Tests 
```release-note
None
```

net: complete some definitions

---

pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet

Problem Summary: When testing in TiDB cloud, `.*` is needed (grafana definition is different on Cloud, there are some hacks). It is wrongly copied back to the original file causing problems.
Tests 
```release-note
None
```

metrics: correct a typo

---

cmd/tiproxy/main.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/server.go

Issue Number: close #256
Add uptime and cpu limit to grafana to help diagnosis.
Add uptime and cpu limit to grafana.
Tests 
From `http://127.0.0.1:3080/api/metrics/`:
```
tiproxy_server_maxprocs 8
```
The grafana doesn't show cpu or uptime data when I start it from TiUP.
```release-note
None
```

metrics: add uptime and cpu limit to grafana

---

pkg/manager/cert/manager.go
pkg/manager/router/backend_observer.go
pkg/manager/router/metrics.go
pkg/metrics/backend.go
pkg/metrics/balance.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/server.go
pkg/metrics/session.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/metrics.go
pkg/server/server.go

Issue Number: close #260
Currently, there are some problems of metrics:
- The avg duration and get backend duration is wrong
- We cannot inspect the latency from each tiproxy to each tidb, which may be affected by cross AZ network
- Lack of metrics that used for alert
- Fix avg duration and get backend duration
- Add ping duration from each tiproxy to each tidb
- Add server start event, load cert err, get backend fail counter, which are used for alert
- Other experience optimization, such as add more legends, change OPM to counter, etc.
Alert rules will be added in another PR.
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.htm …

metrics: add more metrics and fix some metrics

---

pkg/manager/router/backend_selector.go
pkg/manager/router/metrics.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #262 
The backends are unbalanced when the workload starts because the router doesn't update the backend scores in time.
- Add `backendWrapper.connScore` to indicate the scores of backends to replace `connList.Len()` and update it in time.
- `backendWrapper.connList` now only contains the connections that are currently on the backend, which is more straightforward and easier to read.
- Only remove the backend from the list when it's really useless. Do not return error when the backend is not found, add it back and log it.
Tests 
1. Start a cluster with 2 backends
2. Run sysbench with 100 threads
3. Grep the connection count of each backend from the log, and it's 50-50.
Please refer to [Release Notes …

router: fix backends are unbalanced when the workload starts

---

docker/Dockerfile

Problem Summary: It does not build on old docker.
What is changed and how it works: Directory needs to end with a `/`.
Tests 
```release-note
None
```

docker: fix script on some older docker builder

---

lib/config/proxy.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/packetio_mysql.go
pkg/proxy/net/packetio_test.go
pkg/proxy/proxy_test.go
pkg/server/server.go

Issue Number: close #266
Support customize server version
- Server version is set by `HandshakeHandler`
- For the default handler, the server version is set in config
- Rename `testXXX` to `XXX` because they are not used for testing
Tests 
```release-note
None
```

*: customize server version

---

Makefile
conf/proxy.toml
go.sum
lib/config/proxy.go
lib/go.mod
lib/go.sum
lib/util/security/cert.go
lib/util/security/cert_test.go
lib/util/security/tls.go

Issue Number: ref #264
Problem Summary: Make min-tls-version configurable. Also removed two useless functions.
Tests 
```release-note
Add `min-tls-version` config in security config
```

lib: configurable TLS version

---

conf/proxy.toml
lib/config/proxy.go
pkg/proxy/proxyprotocol/listener.go
pkg/proxy/proxyprotocol/listener_test.go
pkg/server/api/http.go
pkg/testkit/main.go

Issue Number: ref #245
Problem Summary: If `NLB` enabled with proxy-protocol, the HTTP port may be sent PPv2 headers. This PR added the support.
Tests 
```release-note
Add support of proxy-protocol for HTTP API port
```

server: add proxyprotocol to http

---

pkg/proxy/backend/backend_conn_mgr.go

move OnConnClose before Swap, because OnConnClose may call backendIO conn like ServerAddr()
Tests 
```release-note
None
```

net: move OnConnClose before Swap

---

pkg/manager/router/metrics.go
pkg/metrics/backend.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet

Issue Number: close #279 
- `Get Backend Count` shows 2 `succeed` without instance names
- `Ping Backend Duration` shows double legends, one is 2s and one is a normal value
- Add instance name to `Get Backend Count`
- Remove `res` label from `Ping Backend Duration`
Tests 
```release-note
None
```

metrics: fix metrics `Get Backend Count` and `Ping Backend Duration` 

---

pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/manager/router/router_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/net/mysql.go

Issue Number: close #272, #217
- When a client connects to the dedicated tier, the server version is always `5.7.25-TiDB-None`
- We can't see why TiProxy thinks a TiDB is down when troubleshooting
- Replace `BackendStatus` with `backendHealth` to store `serverVersion` and `pingErr`
- Read the server version from the backend during health checks
- Send the server version of any backend to the client when handshake. It may be wrong when there are multiple versions running
- Log the error why TiProxy can't connect to TiDB when TiDB is removed from the router
Tests 
1. Start a TiDB cluster with v7.0.0
2. Start a MySQL client to connect to it and the client shows `Server version: 5.7.25-TiDB-v7.0.0 TiDB Server (Apache License 2.0) Community …

router, backend: show server version from TiDB

---

lib/util/errors/error.go
lib/util/errors/error_test.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/error.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go

Issue Number: close #283
TiProxy encounters an error during parsing attributes and it panicked.
- Add a Warning type and a user error msg
- Ignore the error during parsing attrs
Tests 
```release-note
None
```

backend: ignore parsing attrs error during handshake

---

pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go

Tests 
```release-note
None
```

router: add RefreshBackend method for Router interface

---

.github/workflows/release.yaml
.gitignore
.goreleaser.yaml

Problem Summary: Release binaries on pushing tags.
Tests 
```release-note
None
```

add goreleaser

---

pkg/proxy/backend/authenticator_test.go
pkg/proxy/backend/testsuite_test.go

Issue Number: close #295
- The result of the function `getCfgCombinations` is wrong: the slice of `append(o, cfg)` is reused and thus overwrites previous slices, so the test doesn't cover all the cases.
- The cfgOverriders are wrong. E.g. `cfg.clientConfig.capability = defaultTestClientCapability & ^pnet.ClientPSMultiResults` overwrites other capabilities. It should be `cfg.clientConfig.capability &= ^pnet.ClientPSMultiResults` to only change the current capability. It also doesn't cover all the cases.
- Fix `getCfgCombinations`.
- Fix cfgOverriders.
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a quality …

backend: fix authenticator tests

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/backend/error.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/error.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_mysql.go
pkg/proxy/net/packetio_test.go

Issue Number: close #188 
Some errors are not returned to the client, compared with TiDB.
- Move `UserError` from package `backend` to `net` because `net` uses it.
- Return `ErrNotSupportedAuthMode` to the client when frontend capability mismatches. This is consistent with TiDB.
- Return `ErrMalformPacket` when packet size is less than 32. This is consistent with TiDB.
- Return error to the client when TLS handshake fails. This is consistent with TiDB.
- Embed logger into PacketIO.
Tests 
```release-note
None
```

backend, net: return handshake errors to the client

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/authenticator_test.go

Issue Number: close #302
Currently, the TLS config between client and TiProxy is specified by the client, the TLS between TiProxy and TiDB is always disabled.
In the current implementation, the TLS config between TiProxy and TiDB is specified by TiProxy config. However, what we want is to keep consistent with client -> TiProxy. That is:
- If client->TiProxy is enabled, TiProxy -> TiDB is also enabled
- If client->TiProxy is disabled, TiProxy -> TiDB is also disabled
Enable TLS between TiProxy and TiDB when:
- client enables TLS
- proxy configured TLS certs.
- backend supports TLS
This is compatible with both serverless and dedicated tiers.
However, this makes `RequireBackendTLS` sometimes useless: it requires TLS from the backend but it …

backend: keep backend TLS config consistent with frontend TLS config

---

Makefile
cmd/tiproxy/main.go
go.mod
go.sum
lib/go.mod
lib/go.sum
lib/util/retry/retry.go
lib/util/sys/sys.go
pkg/manager/infosync/etcd.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_fetcher_test.go
pkg/server/server.go
pkg/util/versioninfo/versioninfo.go

Issue Number: close #307
If we support self-hosted deployment, we need to support TiDB Dashboard and information_schema.cluster_xxx tables. These features require fetching TiProxy addresses. The most straightforward way is to register TiProxy in the ectd of PD, just like what TiDB does.
- Register info and ttl into PD by `InfoSyncer`
- Move `InitEtcdClient` from `router` to `infosync`
TODO:
- Move more etcd code from `router` to `infosync`. `PDFetcher` should call `infosync` to get TiDB topology.
Tests 
Start TiProxy and check etcd entry from PD:
```
etcdctl get --prefix /topology/tiproxy
/topology/tiproxy/192.168.0.101:6000/info
{"version":"topo","git_hash":"66d42d553315fd26a3bbd677036ec211e2b49d86-dirty","ip":"192.168.0.101","port":"6000 …
```

infosync, router: register TiProxy to ETCD

---

go.mod
lib/config/namespace.go
pkg/manager/infosync/etcd.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/namespace/manager.go
pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_fetcher_test.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router_test.go
pkg/server/server.go

Issue Number: close #308
- If TiDB is down, its TTL info is erased automatically after TTL, so there's no need to check tombstone topologies.
- `PDFetcher` is coupled with etcdClient, making it hard to test.
- Remove tombstone check
- Move all etcd related code into `infosync`
- `PDFetcher` uses `InfoSyncer` to fetch topologies
- Mock a `TopologyFetcher` in the router tests so that it's unware of etcd
Tests 
1. Start a TiDB cluster and TiProxy
2. TiProxy logs `update backend`
3. Scale out a TiDB
4. TiProxy logs `update backend`
```release-note
None …
```

infosync, router: remove tombstone check for TiDB topology

---

go.mod
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

Issue Number: close #316 
Previously, `/topology/tiproxy/xxx/info` won't be erased to act the same as TiDB (I don't know why TiDB doesn't erase it). However, TiDB uses `/topology/tiproxy/xxx/info` for `cluster_info`, so it should be erased when it's down.
- Set lease for `/topology/tiproxy/xxx/info`
- Delete `/topology/tiproxy/xxx/info` when `InfoSyncer` shuts down
Tests 
```release-note
None
```

infosync: remove topology info after TiProxy shuts down

---

lib/util/logger/logger.go
lib/util/security/cert_test.go
lib/util/systimemon/systime_mon_test.go
pkg/manager/cert/manager_test.go
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go
pkg/manager/config/manager_test.go
pkg/manager/config/namespace_test.go
pkg/manager/infosync/info_test.go
pkg/manager/router/backend_fetcher_test.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router_test.go
pkg/metrics/metrics_test.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/net/packetio_test.go
pkg/proxy/proxy_test.go

Issue Number: close #321
- If the log file is in the same directory as the config file, TiProxy reloads the config file once the log outputs, and reloading itself causes log output, which is a dead loop.
- If the directory is removed and then both the directory and the file are created within 200ms, the ConfigManager doesn't receive an event.
- Check the file name for the watch event
- Reload events if watch list is empty before adding
- Support searching logger for test
Tests 
```release-note
None
```

config: skip irrelevant config file events

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/authenticator_test.go

Issue Number: close #332
When TiProxy handshakes with TiDB, it sends `auth_plugin=unknown_auth_plugin` and `auth_data=nil`. TiDB sees that `auth_data=nil` and then sets `using password` to `NO`.
Pass `authData` to TiDB for the first handshake.
Tests 
```
mysql -h127.1 -udummy -P6001 -pdummy
mysql: [Warning] Using a password on the command line interface can be insecure.
ERROR 1045 (28000): Access denied for user 'dummy'@'127.0.0.1' (using password: YES)
mysql -h127.1 -udummy -P6001
ERROR 1045 (28000): Access denied for user 'dummy'@'127.0.0.1' (using password: NO)
```
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a …

backend: fix `using password` in the error message is wrong

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/packetio_mysql.go
pkg/proxy/net/packetio_test.go

Issue Number: close #345
Problem Summary: Pass a real connection id.
Tests 
```release-note
None
```

proxy: use a real proxy conn id

---

lib/config/proxy.go
lib/util/security/cert.go
lib/util/security/tls.go
lib/util/security/tls_test.go

Issue Number: close #337
TiDB reports warnings when TLS version is below 1.2: https://github.com/pingcap/tidb/blob/master/util/misc.go#L499
But TiProxy doesn't: https://github.com/pingcap/TiProxy/blob/main/lib/config/proxy.go#L114
TiProxy can add the warning to keep consistency.
- Move parsing TLS version from `config` to `security` because it can import logger.
- Report warning if necessary.
Tests 
```release-note
None
```

security: report warning when TLS version is below 1.2

---

Makefile
pkg/server/server.go
pkg/util/versioninfo/versioninfo.go

Issue Number: close #286
Print more info about build and runtime so that we can reproduce the bugs locally with the same environment.
- Change `VERSION` from git branch to git tag, and add `BRANCH` to keep the same with TiDB.
- Add more fields such as build time, go version, os, and arch.
- Print `Welcome to TiProxy` so that we can search the restart event by log.
Tests 
```
zhangmingdeMacBook-Pro:tiproxy zhangming$ make
go build -gcflags '' -ldflags ' -X "github.com/pingcap/tiproxy/pkg/util/versioninfo.TiProxyVersion=v0.1.1-14-g6194ad1" -X "github.com/pingcap/tiproxy/pkg/util/versioninfo.TiProxyGitBranch=print_info" -X "github.com/pingcap/tiproxy/pkg/util/versioninfo.TiProxyGitHash=6194ad15119645595ce5ee56e09b3a78c3170610" -X …
```

server: print more info about build and runtime

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/net/packetio_mysql.go
pkg/proxy/net/packetio_test.go

Issue Number: close #356
Wrong format: `ERROR 1105 (HY000): Unknown error%!(EXTRA string=Verify TiDB capability failed, please upgrade TiDB)`
- Use `NewDefaultError` and `NewError` in `github.com/go-mysql-org/go-mysql/mysql` because they handle both formatted and unformatted error messages.
- Replace some constants from `tidb/parser/mysql` to `proxy/net` or `github.com/go-mysql-org/go-mysql/mysql`.
Tests 
```release-note
None
```

net, backend: fix wrong format in error packet

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/authenticator_test.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/error.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_proxy_test.go

Issue Number: close #312
When the TiDB disables TLS and TiProxy enables require-backend-tls, the client receives error `(1105, 'Verify TiDB capability failed, please upgrade TiDB')`. This makes users confused when users deploy the TiDB cluster by themselves. We should tell them that TiDB should enable TLS.
- Change error message when either TiDB or TiProxy doesn't enable TLS
Tests 
1. set `require-backend-tls = true`
2. Disable TiDB TLS
3. Connect with client and see error: `ERROR 1105 (HY000): Require TLS config on TiDB when require-backend-tls=true`. In the log: `[new connection failed] [connID=0] [client_addr=127.0.0.1:53490] [proxy-protocol=false] [backend_addr=127.0.0.1:4000] ["quit source"="proxy error"] [error="backend doesn't …

backend: refine the error message when require TLS

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor.go
pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go

Issue Number: close #355 
- Connection attributes in COM_CHANGE_USER are not saved, so the connection attrs may be wrong after session migration.
- Parse connection attrs in COM_CHANGE_USER, passes it to TiDB (previously not), and sends it to TiDB in the second handshake.
- After COM_CHANGE_USER, migrate the session if needed. Previously it didn't check the redirection signal after COM_CHANGE_USER.
- Add comments for why we need another switch-auth request for COM_CHANGE_USER. The reason is here: https://github.com/pingcap/tiproxy/issues/127#issuecomment-1715308573
Tests 
Integration test: testBug19354014 in JDBC test. …

backend, net: support connection attrs in COM_CHANGE_USER

---

Makefile
docker/Dockerfile

Problem Summary: Missing branch variable in docker build
Tests 
```release-note
None
```

*: fix docker file for new arg

---

pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

Issue Number: close #375
`InfoSyncer.removeTopology()` reports `context deadline exceeded` because it's too slow.
- Add stack to etcd errors
- Increase the put timeout
- Ignore the ContextDeadlineExceed error
Tests 
```release-note
None
```

infosync: increase timeout for `infosync` tests

---

pkg/proxy/net/compress.go
pkg/proxy/net/compress_test.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go

Issue Number: close #377
- The uncompressed sequence is incorrectly set before writing: it should be set before writing the uncompressed packet, rather than writing the compressed packet.
- The compressed sequence is set to 0 when the uncompressed sequence overflows. `SetSequence()` mistakenly set both the compressed and uncompressed sequences to 0.
- Move `BeginRW` from `compressedReadWriter` to `PacketIO` so that the uncompressed sequence can be set before writing the uncompressed packet.
- Add a `ResetSequence()` and only set the compressed sequence to 0 when a new command begins.
Tests 
Tested with jdbc-test:
- `ConnectionRegressionTest#testBug11237`
- `ConnectionTest#testCompression`
- `ConnectionTest#testUseCompress`
Test with …

net: fix packet sequence when sequence overflows

---

conf/proxy.toml
lib/config/proxy.go
lib/config/proxy_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/compress.go
pkg/proxy/net/compress_test.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/proxy.go
pkg/proxy/net/proxy_test.go
pkg/proxy/net/tls.go
pkg/proxy/net/tls_test.go
pkg/proxy/proxy.go

Issue Number: close #381 
`WritePacket` and `ReadPacket` become the hot path when there are many rows returned, so this code should be optimized:
- `WriteOnePacket` calls 2 `NewReader` and that allocates memory twice.
- `ReadPacket` grows slice in `data = append(data, buf)`, which is unncessary.
- `var header [4]byte` escapes to the heap because `header` is passed as a parameter to other functions.
- The read/write buffer size is 16K, which means for 1000 rows, it calls syscall `read`/`write` 8 times.
- `io.ReadFull` contains unnecessary boundary checks, function calls, and interface conversion.
Optimization:
- Replace `io.Copy` with `readWriter.Write` to remove `NewReader`.
- Do not call `data = append(data, buf)` for the first packet.
- …

net, config: optimize read and write packets

---

pkg/server/api/config.go

Issue Number: close #384
Problem Summary: as title
Tests 
```release-note
add ?format= query parameter for /api/admin/config
```

api: add json format response

---

lib/util/sys/sys.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

Issue Number: close #383
Problem Summary: when tiproxy listens on `127.0.0.1:2379`, it also tries to report another unicast IP, e.g. `192.168.4.43`. This does not make sense.
Tests 
```release-note
None
```

manager: get unicast ip only when the config one is not

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/handshake_handler.go

In our severless use case, sometimes tiproxy may connect to the wrong tidb (other user's instance). In this case, we hope that tiproxy can automatically reconnect for certain specific error types, instead of returning the errors to the client.
Tests 
```release-note
None
```

auth: reconnect backend

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/cmd_processor_query.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/net/compress.go
pkg/proxy/net/error.go
pkg/proxy/net/mysql.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_test.go
pkg/proxy/net/proxy.go
pkg/proxy/net/tls.go
pkg/util/bufio/bufio.go

Issue Number: close #381
The performance is still not good enough. We can just forward the packets between connections and avoid allocating memory and copying data.
- Add `PacketIO.ForwardUntil` and call it in `CmdProcessor.forwardUntilResultEnd`. `ForwardUntil` only allocates memory in the last packet. `ForwardUntil` mainly calls `Writer.ReadFrom` to copy data because reader and writer.
- Copy Golang `bufio.go` to TiProxy because `Writer.ReadFrom` always calls `TCPConn.ReadFrom`, which calls sys calls and skips the buffer. We always need the buffer and I can't find a replacement of `bufio`.
- Add `ReadFrom` for all the `packetReadWriter` implementations.
- Modify the parameters of `IsXXXPacket` because we only know the length and first …

backend, net: optimize read/write connection by forwarding packets

---

pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go
pkg/proxy/proxy.go

Issue Number: close #369
Some client versions are in the connection attributes. If we can log them once the connection is created, it might be helpful for troubleshooting.
- Move the log `connected to backend` after the connection is established.
- Add client names and versions in the log.
Tests 
```
[2023/11/08 16:25:28.157 +08:00] [INFO] [main.proxy.conn] [client/client_conn.go:52] [connected to backend] [connID=5] [client_addr=127.0.0.1:65006] [addr=0.0.0.0:6000] [client_version=8.1.0] [client_name=libmysql] [capability=CLIENT_LONG_PASSWORD|CLIENT_LONG_FLAG|CLIENT_CONNECT_WITH_DB|CLIENT_LOCAL_FILES|CLIENT_PROTOCOL_41|CLIENT_SSL|CLIENT_TRANSACTIONS|CLIENT_SECURE_CONNECTION|CLIENT_MULTI_STATEMENTS|CLIENT_MULTI_RESULTS|CLIENT_PLUGIN_AUTH|C …
```

backend, net: log client versions

---

lib/config/namespace.go
lib/config/namespace_test.go
lib/config/proxy.go
lib/config/proxy_test.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/api/namespace_test.go
pkg/server/api/server.go
pkg/server/server.go

Issue Number: close #94
- Some configurations can not be reloaded dynamically
- Some configurations may not be used. This will be a burden after GA.
- Remove `selector-type` because it's useless
- Make `require-backend-tls` able to be hot reloaded
- Remove `server-version`: the router reads the TiDB version and doesn't need a configured one
- Remove `api.user`, `password`, and `enable-basic-auth`: TiDB doesn't have these configs
- Make `metrics` able to be hot reloaded
Tests 
```release-note
None
```

config: support online reload for some config

---

pkg/manager/infosync/info_test.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go

Issue Number: close #374
- `TestHandlerReturnError` takes 15s
- `TestEtcdServerDown4Sync` takes 17s
- Add `ConnectTime` to `BCConfig` so I can make the timeout shorter in `TestHandlerReturnError`. I prefer not to put it into configuration because connection timeout barely happens in self-hosted deployment.
- Reduce loops from 5 to 1 for `TestEtcdServerDown4Sync`.
Tests 
```release-note
None
```

backend, infosync: optimize `TestHandlerReturnError` and `TestEtcdServerDown4Sync`

---

conf/proxy.toml
lib/config/proxy.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/api/config_test.go

Issue Number: close #399
On the cloud, NLB takes around 90s to mark TiProxy offline after TiProxy shuts down the HTTP port. During this process, new connections are denied.
- Only reject new connections after `graceful-wait-before-shutdown`, not before
- Add a configuration `graceful-close-conn-timeout`. After `graceful-wait-before-shutdown`, reject new connections and close connections that have finished transactions, until `graceful-close-conn-timeout` ends
Tests 
```release-note
None
```

proxy, config: add config `graceful-close-conn-timeout`

---

conf/proxy.toml
lib/config/proxy.go
lib/config/proxy_test.go
pkg/manager/cert/manager.go
pkg/manager/cert/manager_test.go
pkg/proxy/proxy.go
pkg/server/api/config_test.go
pkg/server/api/server.go

Issue Number: ref #402 
Problem Summary: Solving problems where users want tls-client-authentication, while tiproxyctl cant prove certs for HTTP status port. It is implemented by renaming `peer-tls`(useless and deprecated now) to `server-http-tls`.
Tests 
```release-note
http port now uses a separate security config server-http-tls
```

conf: use server-http-tls to specify http security | tidb-test=pr/2248

---

pkg/manager/router/backend_observer.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go

Issue Number: close #408
- When the connection begins redirection, the target backend may become unhealthy. This will introduce unnecessary errors.
- In `ensureBackend`, the newly added backend may be removed by `adjustBackendList`.
- Pass `BackendInst` interface (instead of addr) to the `BackendConnMgr` in `Redirect()`
- Check the health by `BackendInst.Healthy()` before redirection. If it's unhealthy, abort redirection
- Add locks to `backendWrapper` because `status` may be read and written concurrently
- Add a parameter `removeEmpty` to `adjustBackendList` and pass `false` to it in `ensureBackend`
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/relea …

router, backend: check target health before redirection

---

pkg/proxy/backend/authenticator_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/cmd_processor.go
pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/cmd_processor_query.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/backend/error.go
pkg/proxy/backend/handshake_handler.go
pkg/proxy/backend/mock_client_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go
pkg/proxy/net/server_status.go

Issue Number: close #358
Using `tidb/parser/mysql`, `go-mysql-org/go-mysql/mysql`, and `pnet` at the same time may cause problems, such as `errors.Is(err, mysql.ErrMalformPacket)` may unexpectedly return false.
- Add `server_status.go`
- Replace most of the usage of `tidb/parser/mysql` with `go-mysql-org/go-mysql/mysql` and `pnet`
Tests 
Code refactor, no tests.
```release-note
None
```

backend, net: replace tidb/parser/mysql

---

conf/proxy.toml
lib/config/proxy.go
lib/config/proxy_test.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/api/config_test.go
pkg/server/server.go

Issue Number: close #411
- `require-backend-tls` is more like a security config
- `require-backend-tls` is true by default, which causes some compatible problems when updating it
- Move `require-backend-tls` from `proxy` section to `security`
- Change the default value of `require-backend-tls` to false
Tests 
```shell
tiup playground v7.5.0 --tiproxy 1 --tiproxy.binpath /Users/zhangming/gopath/src/github.com/pingcap/tiproxy/bin/tiproxy --tiproxy.config cfg --tiflash 0
cat cfg
[proxy]
require-backend-tls = false
```
This proves that it's compatible with the previous config.
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to …

config: move require-backend-tls from proxy to security

---

pkg/manager/namespace/manager.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/health_check.go
pkg/manager/router/health_check_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Issue Number: close #422
The serverless tier needs a customized health check function to check K8S pod health.
- Add an interface `HealthCheck` and its implementation `DefaultHealthCheck`.
- Pass a `HealthCheck` to `ScoreBasedRouter` and `BackendObserver`.
- Decouple the tests of `BackendObserver` and `HealthCheck`.
Tests 
```release-note
None
```

router: add customized health check function

---

pkg/server/api/server.go

Issue Number: close #425 
Currently, we are using `/api/debug` and `/api/metrics`, which are inconsistent with other components. Thus, TiDB Operator, TiUP, and Dashboard need to handle it specially.
Add `/debug` and `/metrics`.
Tests 
```
zhangmingdeMacBook-Pro:tiproxy zhangming$ curl http://127.1:3080/debug/pprof/goroutine > g
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100  5137    0  5137    0     0   584k      0 --:--:-- --:--:-- --:--:-- 2508k
zhangmingdeMacBook-Pro:tiproxy zhangming$ curl http://127.1:3080/metrics > m
% Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
Dload  Upload   Total   Spent    Left  Speed
100    44  100 …
```

api: add /debug and /metrics

---

pkg/manager/router/health_check.go

Issue Number: close #428
The status path is wrong. Maybe it's modified by IDE by mistake.
Fix the status path.
Tests 
1. Start a TiDB cluster
2. Start the TiProxy
3. Connect to TiProxy and query
```release-note
None
```

router: fix status path of TiDB

---

pkg/manager/cert/manager_test.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/health_check.go
pkg/manager/router/health_check_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/backend/common_test.go
pkg/proxy/backend/testsuite_test.go

Issue Number: close #432, #433, ref #434
- Some tests failed in CI
- A previous PR mistakenly updated comments when IDE refactored variable names
- Fix data race in `TestConcurrency`
- Fix `TestRotate`. I guess it's due to timeout but I can't guarantee. I'll reopen the issue if it happens again
- Add logs to `TestConnAttrs`. I don't know the reason yet.
- Revert the comments mistakenly updated by a previous PR
Tests 
```release-note
None
```

router: fix TestConcurrency

---

Makefile
go.mod
go.sum
lib/config/proxy.go
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go
pkg/manager/config/manager_test.go

Issue Number: close #444
Currently `TestFilePath` frequently fails in CI because of the concurrency issue, which was commented in the code.
- Deprecate the watcher way and simply check the file modify time periodically. If the modify time changes, reload the file.
- Only check headers for new files in Makefile
Tests 
```release-note
None
```

config: check mod time

---

go.mod
go.sum
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go

Issue Number: close #444
#445 has another bug: the accuracy of file modify time is 1ms. The file may be updated twice in 1ms and TiProxy may fail to load the latest one.
- Revert to the watch config file way
- Fix the concurrency issue in this way: if there's a watch error, in the next tick, if adding the watch file succeeds, reload it.
- Make the tick interval configurable and set it to 1s by default
Tests 
```release-note
None
```

config: revert to watch config file and fix the concurrency issue

---

lib/config/proxy.go
pkg/server/api/config_test.go

Issue Number: ref https://github.com/pingcap/tidb/issues/36036
[IETF RFC 8996](https://www.rfc-editor.org/rfc/rfc8996.html#name-do-not-use-tls-11) says TLSv1.1 and older should not be used by default. 
This changes the minimum TLS version to TLSv1.2.
Tests 
```release-note
The minimum TLS version was changed to TLSv1.2. This can be changed in the configuration file.
```
> [!WARNING]
> This change should be clearly listed in release notes etc as depending on the MySQL driver and connection configuration this might lead to problems.

Change MinTLSVersion to TLSv1.2

---

pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Issue Number: close #448
There were 2 ways to update the connection score correctly when a connection closes after receiving a redirection signal:
- The connection passes the target backend to the router when it closes
- The router requests for the target backend when the connection closes
However, both these 2 ways are removed, and the connection score is incorrectly maintained.
Maintain the target backend in the router itself. When a connection is closed during redirecting, get the target backend from the router itself.
Tests 
```release-note …
```

router: fix connection score becomes wrong when a connection closes during redirecting

---

pkg/server/server.go

Issue Number: close #453
Problem Summary: The root cause that tiup-cluster did not print the welcome log is that, tiproxy prints the message to stdout, which goes to system units.
And it is basically impossible/very hard to redirect that to the log file on tiup-cluster. Instead, we just print the log after config initialization,
Tests 
```release-note
None
```

log: print welcom after config init

---

pkg/manager/router/router_score.go

Issue Number: close #458
When the connection score is updated, the backend is not reordered. Thus, subsequent rebalance may not work.
Adjust the backend order after the connection score is updated.
Tests 
Before this PR, `TestBackendScore` fails most of the time.
After this PR, `TestBackendScore` always succeeds.
```release-note
Fix that rebalance may not work after session migrations are interrupted.
```

router: fix backend scores are not ordered

---

lib/util/retry/retry.go
pkg/manager/infosync/info_test.go

Issue Number: close #452
`TestClientDown4Sync` sometimes fails because the TTL info is not erased after the etcd client is down.
- Set longer wait duration
- Avoid unnecessary retrial by checking context before the first retrial
Tests 
```release-note
None
```

infosync: set longer duration to stabilize tests

---

.gitignore
pkg/manager/router/backend_observer.go
pkg/manager/router/health_check.go
pkg/manager/router/metrics.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/metrics.go
pkg/util/monotime/monotime.go
pkg/util/monotime/monotime_test.go

Issue Number: ref #420 
We're adding more and more metrics and the overhead of time.Now() is getting more.
time.Now() involves wall time and nanotime, but we only need nanotime to calculate duration.
Replace time.Time with monotime.Time.
Tests 
Benchmark results:
```
BenchmarkGoNow
BenchmarkGoNow-8       	13206856	        82.03 ns/op
BenchmarkMonoNow
BenchmarkMonoNow-8     	33960902	        34.73 ns/op
BenchmarkGoSince
BenchmarkGoSince-8     	 9926468	       123.3 ns/op
BenchmarkMonoSince
BenchmarkMonoSince-8   	15168806	        66.29 ns/op
``` …

router, backend: replace time.Time with mono-time to optimize duration calculation

---

pkg/manager/router/router_score.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/client/client_conn.go
pkg/proxy/proxy.go

Issue Number: close #462 
There are too many logs, e.g. new connection, close connection, begin redirect connection, redirect succeeds.
Change some log level from info to debug
Tests 
Connect to TiProxy and check logs.
```release-note
Change the log level of some logs from info to debug
```

*: change some log level from info to debug

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #470 
Currently, `resetCheckBackendTicker` uses around 1.4% CPU usage. It is called for every command, which is unnecessary.
Just update `lastActiveTime` after each execution. The ticker just checks if it exceeds the interval.
This ticker will also be used for #414 
Tests 
Run sysbench and it proves that the performance doesn't change much. It's expected.
```release-note
None
```

backend: optimize `resetCheckBackendTicker`

---

go.mod
go.sum
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go

Issue Number: close #468 
When the watched directory is removed and recreated immediately, sometimes fsnotify doesn't report an error and TiProxy is not aware of file change.
Simply reload the file periodically and set config if the file content changes.
Tests 
```release-note
- Fix the bug that the config file may not be reloaded if the directory is removed and recreated immediately.
```

config: replace fsnotify with reloading config file periodically

---

pkg/manager/router/router_score.go
pkg/proxy/backend/authenticator.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/testsuite_test.go
pkg/proxy/backend/util.go
pkg/proxy/net/packetio.go
pkg/proxy/net/packetio_mysql.go
pkg/proxy/net/packetio_test.go

Issue Number: close #472
When there are many idle connections on a TiProxy instance, the CPU usage jitters every 2 minutes because of GC.
- Replace `time.After` to `time.Ticker`
- Replace `sync.Map` with `map` and `sync.Lock`
- Other optimizations like `header`, `salt`
Tests 
Run and profile to see the frame graph and the overhead disappears.
alloc_objects:
inuse_objects:
```release-note
- Reduce GC CPU usage by 1% in the case of plenty of connections
```

*: reduce memory allocation for plenty of idle connections

---

pkg/manager/router/backend_selector.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #414 
Every time a backend status changes, `Router` notifies `BackendConnManager`. This makes them too coupled.
- `Router` and `BackendSelector` return `BackendInst` to `BackendConnManager`
- `BackendConnManager` periodically reads health from `BackendInst` and sets keepalive
- `BackendSelector` moves `Reset()` into `Next()` to simplify interfaces
Tests 
```release-note
None
```

router, backend: remove NotifyBackendStatus

---

pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/session.go
pkg/metrics/traffic.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/metrics.go
pkg/proxy/backend/metrics_test.go
pkg/proxy/net/packetio.go

Issue Number: close #406 
We need metrics for traffic and handshake.
Add metrics for traffic and handshake.
Tests 
```release-note
- Add metrics for traffic and handshake.
```

backend, metrics: add metrics for traffic and handshake

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/packetio.go

Issue Number: close #406 
Add more logs for observability.
Add logs:
- the duration and text of the query when TiDB disconnects (may relate to OOM)
- the idle time of the connection when TiDB disconnects (maybe disconnected by TiDB because of wait_timeout)
- report a warning when the sequence mismatches
Tests 
```release-note
None
```

backend, net: add more logs

---

pkg/server/api/config.go
pkg/server/api/config_test.go
pkg/server/api/debug_test.go
pkg/server/api/metrics_test.go
pkg/server/api/namespace_test.go
pkg/server/api/server_test.go

Issue Number: close #483 
`/api/admin/config` doesn't respect `Accept` field in the request header, while some applications may expect a json format.
If `Accept` is `json` or `format` is `json`, return a json format.
Tests 
```release-note
- Support get JSON format config for /api/admin/config by setting Accept='application/json' in the request header
```

api: support get json format for config by setting Accept header

---

pkg/proxy/backend/cmd_processor_query.go
pkg/proxy/backend/cmd_processor_test.go
pkg/proxy/backend/mock_backend_test.go

Issue Number: close #485 
TiProxy doesn't handle errors when processing result sets, and it reports nil pointer reference.
Check the error first.
Tests 
```release-note
- Fix panic when a TiDB fails during session migration.
```

backend: fix panic when reading result set fails

---

conf/proxy.toml
lib/config/proxy.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

Issue Number: close #494
TiProxy registers its IP to ETCD and TiDB/TiDB-Dashboard queries its config/pprof through IP, while the certificates in TiProxy may only contain DNS (especially in k8s) and the query fails.
Add `proxy.advertise-addr` to the config. Later, I'll update TiUP and TiDB-Operator to pass the DNS in the config.
Tests 
```release-note
- Add configuration `proxy.advertise-addr`
```

config, info: add config `proxy.advertise-addr`

---

cmd/tiproxy/main.go

Issue Number: close #494 
For TiDB-Operator, it's not easy to pass `advertise-addr` into the config file.
- Add a cmd argument `advertise-addr`
Tests 
In the TiProxy container logs:
```
starting: tiproxy --config=/etc/proxy/proxy.toml --advertise-addr=basic-tiproxy-0.basic-tiproxy-peer.tidb-cluster.svc
```
Query the TiProxy config:
```
curl http://127.1:3080/api/admin/config/ | grep advertise
advertise-addr = 'basic-tiproxy-0.basic-tiproxy-peer.tidb-cluster.svc'
```
```release-note
- Add a command line argument `advertise-addr`
```

main: add cmd arg `advertise-addr`

---

lib/util/security/cert_test.go

Issue Number: ref #464 
It proves that a cert pool can store multiple CAs and each CA works. It's useful for the design of cert-based auth.
E.g. there are 2 certs: ca1 + cert1 + key1 and ca2 + cert2 + key2
If I put both ca1 and ca2 into the cert pool, the cert pool can verify both cert1 + key1 and cert2 + key2.
Add a unit test.
Tests 
```release-note
None
```

security: add unit test for cert pool

---

lib/config/namespace.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/metricsreader/metrics_reader.go
pkg/manager/metricsreader/metrics_reader_test.go
pkg/manager/metricsreader/mock_test.go
pkg/manager/metricsreader/query_result.go
pkg/manager/namespace/manager.go
pkg/manager/router/backend_observer_test.go
pkg/server/server.go

Issue Number: close #499
TiProxy collects TiDB metrics so that it can balance by CPU, memory, and health.
I do not collect them from TiDB `/metrics` because each response is 800KB, which is too much.
- Read the Prometheus address from etcd.
- Read metrics from Prometheus.
- Add some configurations but not exposed to users.
Tests 
```release-note
None
```

metricsreader, infosync: read metrics from prometheus

---

cmd/tiproxy/main.go

Issue Number: ref #449 
`log_level` and `log_encoder` conflict with the configs which support hot reload. This may confuse users when they update the config file.
Deprecate `log_level` and `log_encoder`. They will be removed in the future.
Tests 
```
$ bin/tiproxy --help
start the proxy server
Usage:
bin/tiproxy [flags]
Flags:
--advertise-addr string   advertise address
--config string           proxy config file path
-h, --help                    help for bin/tiproxy
--log_encoder string      deprecated and will be removed
--log_level string        deprecated and will be removed
-v, --version                 version for bin/tiproxy
$ bin/tiproxy --log_level=debug
// started normally
```
Please refer to [Release Notes …

cmd: deprecate cmd args `log_level` and `log_encoder`

---

go.mod
go.sum
pkg/manager/metricsreader/metrics_reader.go
pkg/manager/metricsreader/metrics_reader_test.go
pkg/manager/metricsreader/mock_test.go
pkg/manager/namespace/manager.go
pkg/manager/namespace/namespace.go
pkg/manager/observer/backend_fetcher.go
pkg/manager/observer/backend_fetcher_test.go
pkg/manager/observer/backend_health.go
pkg/manager/observer/backend_observer.go
pkg/manager/observer/backend_observer_test.go
pkg/manager/observer/health_check.go
pkg/manager/observer/health_check_test.go
pkg/manager/observer/metrics.go
pkg/manager/observer/mock_test.go
pkg/manager/router/metrics.go
pkg/manager/router/mock_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go
pkg/proxy/net/error.go
pkg/testkit/main.go

Issue Number: close #501 
Health check, backend observer, and backend fetcher are independent of the router. Multiple router implementations can reuse the same backend observer.
- Move `HealthCheck`, `BackendObserver`, and `BackendFetcher` from package `router` to `observer`.
- `NamespaceMgr` creates `BackendObserver` and passes it to `ScoreBasedRouter`.
- Move mocked objects to `mock_test.go`.
- Move some common functions to common packages.
Tests 
```release-note
None
```

router, observer: move BackendObserver from package router to observer

---

pkg/manager/metricsreader/metrics_reader.go
pkg/manager/namespace/manager.go
pkg/manager/observer/backend_health.go
pkg/manager/observer/backend_observer.go
pkg/manager/observer/backend_observer_test.go
pkg/manager/router/mock_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_test.go

Issue Number: close #503 
Currently, BackendObserver pushes backend updates to Router. BackendObserver is shared among multiple tenants while Router is private for each tenant. The right way is that Router pulls from BackendObserver.
- ScoredBasedRouter subscribes backend (HealthResult) from BackendObserver
- BackendObserver notifies all the backends to Router, instead of updated backends
Tests 
```release-note
None
```

router, observer: make router pull backends from observer

---

pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go

Issue Number: close #515 
the func metrics_reader.getPromAPI panic if there is no prometheus info in pd
the panic reson as below
net.JoinHostPort(promInfo.IP, strconv.Itoa(promInfo.Port)) panic since it get nil  promInfo when dmr.promFetcher.GetPromInfo(ctx) return  nil,nil
```
// Always refresh the prometheus Address just in case it changes.
func (dmr *DefaultMetricsReader) getPromAPI(ctx context.Context) (promv1.API, error) {
promInfo, err := dmr.promFetcher.GetPromInfo(ctx)   // (promInfo,err) is (nil,nil) when there is no prometheus info in pd
if promInfo == nil && dmr.getPromRes != getPromFail {
dmr.getPromRes = getPromFail
dmr.lg.Warn("get prometheus address fails", zap.Error(err))
}
if err != nil {
return nil, err
}
// TODO: …
```

metricsreader: fix the metrics_reader.getPromAPI fun panic when there is no prometheus info in pd

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/metricsreader/query_result.go
pkg/balance/metricsreader/query_result_test.go
pkg/balance/policy/balance_policy.go
pkg/balance/policy/mock_test.go
pkg/manager/namespace/manager.go

Issue Number: close #519
Support CPU-based balance
- Add a new factor `FactorCPU` that scores backend by CPU usage
- `MetricsReader` doesn't update `QueryResult` if fetching metrics fails so that factors can reuse the old `QueryResult`
- Add some timeouts to existing tests
TODO:
This is not finished because I need some work to match the metric label with the backend address. It's not simple so I'll do it in another PR.
Tests 
```release-note
- Support CPU-based load balance
```

balance: support cpu-based balance

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

Issue Number: close #524 
In https://github.com/pingcap/tiproxy/pull/400, I intended to accept connection during graceful wait so that client connections won't fail during tiproxy shutting down.
However, in https://github.com/pingcap/tiproxy/pull/443, I somehow broke that behavior when I was fixing a data race.
- Do not reject connections during graceful-wait-before-shutdown
- Defer unlocking just in case it panics and all other connections block
Tests 
```release-note
- Do not reject new connections until `graceful-wait-before-shutdown` finishes …
```

proxy: reject connection after graceful wait

---

pkg/proxy/proxy.go
pkg/proxy/proxy_test.go

This is a cherry-pick of #525 
Issue Number: close #524 
In https://github.com/pingcap/tiproxy/pull/400, I intended to accept connection during graceful wait so that client connections won't fail during tiproxy shutting down.
However, in https://github.com/pingcap/tiproxy/pull/443, I somehow broke that behavior when I was fixing a data race.
- Do not reject connections during graceful-wait-before-shutdown
- Defer unlocking just in case it panics and all other connections block
Tests 
```release-note
- Do not reject new connections until …
```

proxy: reject connection after graceful wait (#525)

---

pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/metricsreader/query_result.go
pkg/balance/metricsreader/query_result_test.go
pkg/balance/observer/backend_health.go
pkg/balance/observer/backend_observer.go
pkg/balance/observer/backend_observer_test.go
pkg/balance/observer/health_check.go
pkg/balance/observer/mock_test.go
pkg/balance/policy/balance_policy.go
pkg/balance/policy/mock_test.go
pkg/balance/router/router.go
pkg/balance/router/router_score.go

Issue Number: close #527 
To get the metric for each backend, we need to match the backend label in metrics with the backend address in etcd.
- Add `BackendInfo` to struct `BackendHealth` so that factors can get the IP and status port from `BackendCtx`
- Match the metric label with `BackendCtx`, considering both TiUP and Operator deployment
Tests 
```release-note
None
```

balance: match metric label with backend address

---

pkg/balance/observer/backend_fetcher.go
pkg/balance/observer/backend_fetcher_test.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

remove import "tidb/domain/infosyncin" in  infosync package.
Issue Number: close #523 
define TiDBTopologyInfo to replace TopologyInfo in tidb/domain/infosync
Tests 
```release-note
None
```

infosync:define TiDBTopologyInfo to replace TopologyInfo in tidb/domain/infosync

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/metricsreader/metrics_reader.go

Issue Number: close #530
The PromQL to query CPU is wrong and it's hard to find the reason.
- Fix the PromQL
- Add logs to troubleshoot
- Update retry interval
Tests 
Add E2E tests in endless and CPU-based balance works.
```release-note
None
```

metricsreader, factor: fix wrong PromQL expression

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_location.go
pkg/balance/factor/factor_location_test.go

Issue Number: close #545
I planned to use the label-based balance to implement the location-based balance, but I found 2 things:
- TiDB follower read uses a predefined label `zone` to decide the location, and TiDB-operator only sets TiDB/TiProxy labels that are in `replication.location-labels` in PD.
- To be compatible with the Elastic Group on TiDBCloud, we need both label-based and location-based balance. The priority of label-based balance should be the highest.
Thus, I plan to add another location-based balance and it is based on a predefined label `zone`.
Add factor `FactorLocation` and it is based on a predefined label `zone`.
Tests  …

factor: support location-based balance

---

pkg/balance/factor/factor_conn.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_error.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/mock_test.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go

Issue Number: close #547 
Currently the migration speed has some problems:
- For CPU-based balance, 1 connection per second may be too low if there are many connections
- For health, memory, and error based balance, 10 connections per second is too low.
- For CPU-based balance, the migration speed depends on the overall connection count.
- For health, memory, and error based balance, change it to 1000 connections per second and add a sleep between migrations.
- For CPU-based balance, use `rate[1m]` instead of EMWA algorithm to make it simpler.
- Update some constants.
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to …

factor: update migration speed

---

pkg/balance/factor/factor.go
pkg/balance/factor/factor_conn.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_error.go
pkg/balance/factor/factor_error_test.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_label.go
pkg/balance/factor/factor_location.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/policy/balance_policy.go
pkg/balance/policy/simple_policy.go
pkg/balance/router/mock_test.go
pkg/balance/router/router.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go

Issue Number: close #549 
There are some problems with the current session migration:
- When a backend has something wrong, all the connections are migrated to the same target backend. The target backend may be overloaded
- There is a sleep in the rebalance, which may cause the problem that the lock is held too long
- Rebalance every a short time and migrate only a few connections in each round
- Control the speed in the router, considering both slow migration(like CPU-based) and fast migration(like health-based)
- `BalanceCount()` returns the count per second, instead of per round
- Factors calculate the balance count by the current connection counts
- Fix a deadlock bug in `TestConcurrency`
Tests 
Please refer to …

router, factor: fix the speed control of session migration

---

lib/config/getter.go
pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go
pkg/balance/factor/factor_location.go
pkg/balance/factor/factor_location_test.go
pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/observer/backend_health.go
pkg/balance/observer/backend_observer.go
pkg/balance/observer/backend_observer_test.go
pkg/balance/observer/mock_test.go
pkg/balance/policy/balance_policy.go
pkg/balance/policy/mock_test.go
pkg/balance/policy/simple_policy.go
pkg/balance/policy/simple_policy_test.go
pkg/balance/router/metrics.go
pkg/balance/router/mock_test.go
pkg/balance/router/router.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go
pkg/balance/router/router_static.go
pkg/manager/namespace/manager.go
pkg/metrics/balance.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/traffic.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/metrics.go

Issue Number: close #555
Users may need these metrics for load balance:
- The reasons for connection migration
- Cross-zone traffic
- Add `ConfigGetter` to pull configs instead of pushing configs because #532 
- `BackendObserver` decides backend locality by TiProxy labels and backend labels. This is moved from `FactorLocation` so that both `FactorLocation` and `BackendConnMgr` can know backend locality by `BackendInst`
- Add cross-az traffic and connection migration metrics
Tests 
```release-note
- Add metrics of cross-az traffic and connection …
```

metrics, balance: add metrics for load balance

---

pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go

Issue Number: close #557 
1. v7.5 doesn't support memory quota, so its memory usage is missing and it was taken unhealthy. When TiDB upgrades to v8.1, all the connections will be migrated to the first new version all at once.
2. If the memory usage of all backends is high and then the user scales out a backend, all the connections will be migrated to the first new version all at once.
3. Sometimes TiDB OOM before reaching 100% CPU usage.
1. For the 1st problem, take it healthy when its metric is missing
2. For the 2nd problem, slow down migration when memory usage is high (but memory doesn't increase quickly)
3. For the 3rd problem, adjust the thresholds
Tests  …

factor: update memory-based balance policy

---

pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go

Issue Number: close #559
After replacing the EWMA algorithm with `rate[1m]`, the CPU usage is always stale. When migrating connections from A to B, the smoothed CPU usage of A is higher than B, even if the actual CPU usage of A is lower than B.
- Replace `rate[1m]` to `irate[30s]` to get the latest CPU usage
- Calculate the score and balance count based on the latest CPU usage
- Use the EWMA algorithm to get the smoothed average CPU usage
- When deciding whether to balance, also consider the average CPU usage to avoid CPU jittering too much
Tests  …

factor: use both average usage and latest usage in CPU-based balance

---

pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet

Issue Number: close #542 
Using log2 on the Y axis of some metrics is clearer, especially duration and CPS.
Update metrics json to add `logBase=2`.
Tests 
```release-note
None
```

metrics: set the Y axis of some metrics to logBase=2

---

lib/config/namespace.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/mock_test.go

Issue Number: close #562 
The refresh interval of Prometheus is 15s and the interval for TiProxy reading Prometheus is 15s. Thus, the metric delay is at most 30s.
If TiProxy reads Prometheus every 5s, the max delay is 20s.
- Update the reading metrics interval to 5s
- Do not update the backend snapshot if the metric of this backend is not updated, even if the whole query result is updated.
Tests 
```release-note
None
```

factor: query Prometheus more frequently to update metrics timely

---

pkg/balance/observer/health_check.go
pkg/balance/observer/health_check_test.go

Issue Number: close #567 
TiProxy reports unmarshal body in healthy check failed" when TiDB is graceful shutdown. It's introduced in #510 because it didn't check error correctly.
Return when there's an error.
Tests 
```release-note
None
```

observer: fix TiProxy reports unmarshal body in healthy check failed" when TiDB is graceful shutdown

---

pkg/balance/observer/health_check.go
pkg/balance/observer/health_check_test.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go

Issue Number: close #577 
#510 removes reading one packet from the SQL port, but some TiDB versions don't respond after establishing the TCP connection before finishing loading statistics.
Handshake until TLS is complicated. It needs to consider capabilities like proxy-protocol and TLS. So maybe I'll use another way to detect the validity of TLS certs.
Read one packet from the SQL port in health checking.
Tests 
```release-note
None
```

observer, net: read packet from SQL port in health check

---

pkg/balance/factor/factor.go
pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go
pkg/balance/factor/factor_conn.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_label.go
pkg/balance/factor/factor_location.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/factor_status.go
pkg/balance/factor/factor_status_test.go
pkg/balance/factor/mock_test.go
pkg/balance/policy/balance_policy.go
pkg/balance/policy/simple_policy.go
pkg/balance/router/mock_test.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go

Issue Number: close #570 
In testing I found the migration is not quick enough because:
- Some migrations may fail and retry. This possibility was not considered for migration speed.
- In the rolling upgrade scenario, the target backend had 0 connection at first because it had just started. But my assumption was that the source and target backends have similar connections at first.
Besides, CPU-based balance is too fast because when balanceCount < 1, it is set to 1. So there's at least 15 connections migrated for each metric collection cycle.
- Change the return type of `BalanceCount` from int to float64. E.g. 0.5 means migrating 1 connection every 2 seconds.
- Record the balance count at the beginning of migration for urgent factors, …

factor: update migration speed for factors

---

pkg/manager/namespace/manager.go
pkg/manager/router/backend_fetcher.go
pkg/manager/router/backend_fetcher_test.go
pkg/manager/router/backend_observer.go
pkg/manager/router/backend_observer_test.go
pkg/manager/router/router.go
pkg/manager/router/router_score.go
pkg/manager/router/router_static.go
pkg/manager/router/router_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_backend_test.go
pkg/proxy/backend/session_states.go
pkg/proxy/backend/testsuite_test.go

Problem Summary: 
- Introduce a new feature that TiProxy can pause session.
-  TiProxy store session states when last backend become unhealthy. 
- When the session is saved, tiproxy won't closed client connection when backend connection is closed.
- The session can be restored when client become active again to a new backend.
Tests 
```release-note
None
```

router, backend: pause session when last backend become unhealthy

---

pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go

Issue Number: close #576 
Start a cluster without Prometheus and TiProxy keeps reporting warnings every 5 seconds.
Only report the error once if there are successive errors.
Tests 
```release-note
None
```

metricsreader: only report error once if Prometheus is not deployed

---

pkg/balance/observer/backend_health.go
pkg/balance/observer/backend_observer.go
pkg/balance/observer/metrics.go
pkg/metrics/backend.go
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go

Issue Number: close #582 
The backend metric is never cleared after the backend is down. In auto-scaling workload, the backends change frequently and then the metrics keep growing.
- Purge the backend metrics after it's down for over 2 hours
- Remove the `status` label for `BackendStatusGauge`. `BackendStatusGauge` is not used in Grafana so it's fine.
Tests 
Steps:
1. Update the threshold from 2 hours to 2 minutes and build TiProxy
2. Create a cluster with `tiup playground v8.1.0 --db=2 --tiproxy=1 --tiproxy.version=v1.1.0 --tiflash=0`
3. Run sysbench to create metrics
4. Scale-in the TiDB `127.0.0.1:4001`
5. Check the metrics immediately and `127.0.0.1:4001` existed
```shell
curl -L 127.1:3080/metrics | grep -c 127.0.0.1:4001
204
```
6. …

metrics, observer: purge backend metrics when backend is down for too long

---

go.mod
pkg/manager/elect/election.go
pkg/manager/elect/election_test.go
pkg/manager/elect/mock_test.go
pkg/manager/infosync/etcd.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go

Issue Number: close #587 
`elect.Election` is a general election based on etcd election. It's used for electing VIP later.
- Create `elect.Election`
- Move `CreateEtcdServer` from test file to `etcd.go`
Tests 
```release-note
None
```

elect, infosync: create Election to elect owner

---

pkg/manager/elect/election.go
pkg/manager/elect/mock_test.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/vip/network_test.go
pkg/server/server.go
pkg/server/server_test.go
pkg/util/etcd/etcd.go
pkg/util/etcd/etcd_test.go

Issue Number: close #591 
Integrate VIP manager into the server.
- Create the VIP manager after creating SQL server and close the VIP manager before closing SQL server
- Move etcd-related code from package `infosync` to `util/etcd` so that all other components can call it
- The `Server` creates an etcd client and passes it to the other components so that it doesn't need to pass config or certMgr
- Rename the member of `Server` from uppercase to lowercase
Tests 
```release-note
None
```

server, etcd: integrate vip manager into the server

---

pkg/manager/vip/manager.go
pkg/manager/vip/manager_test.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/server.go

Issue Number: close #593 
Add metric to show the VIP owner
Define `VIPGauge`. It's set to 1 when it's the owner.
Tests 
```release-note
None
```

metrics, vip: add metric to show the VIP owner

---

lib/config/proxy.go
lib/config/proxy_test.go
pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/metricsreader/query_result.go
pkg/balance/observer/backend_fetcher.go
pkg/balance/observer/backend_fetcher_test.go
pkg/balance/observer/mock_test.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/vip/manager.go

Issue Number: close #596 
On the cloud, the Prometheus is inaccessible from TiProxy, so TiProxy can only read from TiDB directly.
- Add `BackendReader` to read metrics directly from backends
- Make `InfoSyncer.GetTiDBTopology` return `TiDBTopologyInfo` because TiProxy doesn't need TTL of TiDB
- Move `GetIPPort` from `InfoSyncer` to `Config`
- Fix the ETCD key path and ID of `VIPManager`
Tests 
```release-note
None
```

metricsreader, observer: read metrics from backend HTTP API

---

pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/balance/observer/health_check.go
pkg/manager/namespace/manager.go
pkg/server/api/backend.go
pkg/server/api/backend_test.go
pkg/server/api/server.go
pkg/server/api/server_test.go
pkg/server/server.go
pkg/util/httputil/http.go
pkg/util/httputil/http_test.go

Issue Number: close #600
Read the backend metrics from the owner because if everyone reads from the backends, the backends may suffer from big pressure if the cluster is large.
- `BackendReader` supports marshaling and unmarshaling backend metric history
- The HTTP API reads metric data from `BackendReader`
- Move the creation of `BackendReader` from `NamespaceManager` to `Server` so that it can be passed to `api.Server`
- Move the common code of reconnection to package `httputil`
- Change the rule key from uint64 to string so that the keys of every TiProxy are the same. The caller is responsible for specifying the rule key
Tests  …

metricsreader, api: read backend metrics from owner

---

lib/config/health.go
lib/config/namespace.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/metricsreader/prom_reader.go
pkg/balance/metricsreader/prom_reader_test.go
pkg/balance/metricsreader/query_result.go
pkg/manager/elect/election.go
pkg/manager/infosync/info.go
pkg/manager/infosync/info_test.go
pkg/manager/namespace/manager.go
pkg/server/server.go

Issue Number: close #605 
When Prometheus is available, read metrics from Prometheus. If not, read from backends.
- Add `PromReader`. `MetricsReader` reads from `PromReader` first, if it fails, reads from `BackendReader`.
- Fix that `BackendReader` doesn't update query results after it reads from the owner.
- Move `HealthCheck` configs from `namespace.go` to `health.go`.
- Fix some query rules that when TiDB has rebooted, the metric value may jump back.
- Change the key of query expressions from `uint64` to `string` so that every TiProxy has the same key.
- Remove `QueryResult.Err` because it's useless.
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/re …

balance, infosync: support reading metrics from both prometheus and backend

---

lib/config/label.go
lib/config/proxy.go
pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go
pkg/balance/metricsreader/mock_test.go
pkg/balance/observer/backend_health.go
pkg/balance/observer/backend_observer_test.go
pkg/manager/elect/election.go
pkg/manager/elect/mock_test.go
pkg/manager/infosync/info.go
pkg/manager/vip/mock_test.go
pkg/server/api/backend.go
pkg/server/api/backend_test.go
pkg/server/server.go
pkg/util/etcd/etcd.go
pkg/util/etcd/etcd_test.go

Issue Number: close #610 
There is some cross-az traffic if the metricreader owner reads from all TiDB when there are hundreds of TiDB in a multi-az cluster.
- Elect a zonal owner for each zone if the zone is set. Otherwise, elect a global owner to read all backends.
- Fix that the `BackendReader` is not set in `ApiServer`.
- Fix that the VIP is not excluded when getting self-IP.
- Extract `etcd.GetKVs` as a common function.
Tests 
```release-note
None
```

metricsreader, elect: read metrics from zone leader

---

pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_cpu_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/mock_test.go

Issue Number: close #612 
Now that the metric may be collected from backends, the interval is not guaranteed. It may be too long or too short. If it's too short, the CPU usage or time to OOM may thrash.
- If the interval of CPU metric is shorter than 1s, do not calculate CPU usage from that metric.
- If the interval of memory metric is shorter than 1s, do not calculate time to OOM from that metric.
Tests 
```release-note
None
```

factor: check the metric interval for CPU and memory-based balance 

---

pkg/balance/metricsreader/backend_reader.go
pkg/manager/elect/election.go
pkg/manager/elect/election_test.go
pkg/manager/vip/manager.go
pkg/manager/vip/manager_test.go
pkg/metrics/grafana/tiproxy_summary.json
pkg/metrics/grafana/tiproxy_summary.jsonnet
pkg/metrics/metrics.go
pkg/metrics/metrics_test.go
pkg/metrics/server.go

Issue Number: close #614 
Show the metrics reader owner on Grafana
- Change `VIPGauge` to `OwnerGauge` so that it's general
- Delete the metric when it's not the owner
Tests 
```release-note
None
```

metrics, elect: Show the metrics reader owner on Grafana

---

lib/util/logger/logger.go
pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/manager/vip/manager.go
pkg/manager/vip/network.go

Issue Number: close #616 
If the value of `step2` is `NaN`, the value of `step1` is ignored either. But the next time `step2` relies on `Step1History` and `Step1History` is always empty.
- Write `Step1History` when `step1` is not `NaN`.
- Refine some error reporting.
Tests 
```release-note
None
```

metricreader: fix that the metrics of CPU and health are not collected

---

pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go
pkg/balance/metricsreader/query_result.go

Issue Number: close #618 
After the query results are returned to factors, the results are still updated by the BackendReader, which may cause data race.
Always generate the query results from scratch and replace the query results all at once so that the query result map won't be updated.
Tests 
```release-note
None
```

metricreader: fix data race in BackendReader

---

lib/cli/util.go
pkg/proxy/backend/backend_conn_mgr.go

Issue Number: close #620 
Third-party tools treat `math/rand` and `unsafe` as insecure packages.
- Replace `unsafe`
- Remove `math/rand`
Tests 
```release-note
None
```

backend, cli: fix vulnerability issues scanned by third-party tools

---

pkg/balance/metricsreader/backend_reader.go
pkg/manager/elect/election.go
pkg/manager/elect/election_test.go
pkg/manager/vip/manager.go
pkg/manager/vip/manager_test.go
pkg/server/server.go

Issue Number: close #624 
When the TiProxy VIP owner shuts down, it deletes VIP while another member adds VIP concurrently. If the new owner adds VIP after the previous deletes VIP, there may be a moment when the clients can't connect to the cluster.
- Resign the owner before graceful wait, delete the VIP after graceful wait.
- Shorten the TTL for VIP owner and metric_reader owner.
Tests 
```release-note
None
```

vip, server: optimize failover for graceful shutdown with VIP

---

.golangci.yaml
pkg/manager/vip/network.go
pkg/manager/vip/network_test.go
pkg/util/cmd/cmd.go
pkg/util/cmd/cmd_test.go

Issue Number: close #628 
If TiProxy is deployed by TiUP, the user typically only has the sudo permission and can't add VIP.
Try to execute `ip addr add`, `ip addr del`, and `arping -U` with `sudo` if the permission is denied.
Tests 
1. Create a user with sudo permission and run TiProxy. It adds VIP successfully.
2. Create a user without sudo permission and it fails to add VIP.
```release-note
None
```

Allow adding VIP if the user has sudo permission

---

pkg/balance/factor/mock_test.go
pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/metricsreader/metrics_reader_test.go
pkg/manager/elect/election.go
pkg/manager/elect/election_test.go
pkg/manager/elect/mock_test.go
pkg/manager/vip/manager.go
pkg/manager/vip/manager_test.go
pkg/manager/vip/mock_test.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/api/backend_test.go
pkg/server/api/config_test.go
pkg/server/api/debug.go
pkg/server/api/debug_test.go
pkg/server/api/metrics_test.go
pkg/server/api/namespace_test.go
pkg/server/api/server.go
pkg/server/api/server_test.go
pkg/server/server.go

Issue Number: close #631 
When PD restarts, although TiProxy retires the VIP after the etcd server is back, it still takes several seconds before the owner is elected, which causes a long failover time.
- `election` only retires when a new owner is elected.
- `election.Close()` doesn't retire, it only resigns the owner. The callers `BackendReader` and `VIPManager` decide when to retire.
- Update the graceful shutdown procedure. `Server` calls `BackendReader.PreClose()`, `VIPManager.PreClose()`, `APIServer.PreClose()`, and `SQLServer.PreClose()` before real shutdown so that elections have enough time to wait for the new owner.
Tests  …

*: retire after a new owner is elected

---

pkg/manager/vip/network_test.go
pkg/util/cmd/cmd.go
pkg/util/cmd/cmd_test.go

Issue Number: ref #628 
Although `"ip" "addr" "add" ...` works on the command line, it fails on `exec.Command(...)`.
Remove quotes for command arguments.
Tests 
Run TiProxy with a non-root user and check if the ip is bound.
```release-note
None
```

cmd: remove quotes for command arguments

---

pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/query_result.go
pkg/balance/metricsreader/query_result_test.go

Issue Number: close #634 
The balance doesn't work because the backend label value doesn't match that in Prometheus.
- Current label name: `tc-tidb-0.tc-tidb-peer.ns.svc:3080`
- Prometheus label name: `tc-tidb-0`
Change the label name from backend address to the pod name.
Tests 
Test in k8s and the CPU is balanced.
```release-note
None
```

metricreader: fix backend label value doesn't match Prometheus in k8s

---

pkg/balance/metricsreader/backend_reader.go
pkg/manager/elect/election.go
pkg/manager/elect/election_test.go
pkg/manager/vip/manager.go
pkg/manager/vip/manager_test.go

Issue Number: close #636 
When closing the election, the metric is not deleted, so both zonal and global owners are shown on Grafana.
- Revert `election.Close()` so that it calls `onRetire` before closing.
- `VIPManager` prevents deleting VIP in `PreClose()` proactively so that the VIP is not deleted before graceful shutdown.
Tests 
```release-note
None
```

elect, vip: fix incorrect metric_reader owner metrics

---

pkg/balance/metricsreader/backend_reader.go
pkg/balance/metricsreader/backend_reader_test.go

Issue Number: close #638 
- When multiple TiProxy read the metrics of the same TiDB, the history may grow longer and longer. This is because the history that is read from the other TiProxy overwrites the local history that is purged.
- When the owner can connect to Prometheus but a member fails to connect to Prometheus, the member reads stale metrics.
- Extract `marshalHistory` and `history2QueryResult` to the common path.
- Call `marshalHistory` and `history2QueryResult` after `purgeHistory`
- Call `readFromBackends` before `readFromOwner`
Tests 
Manual test:
Follow the steps described in the issue and check the data from `/api/backend/metrics` …

metricreader: fix that sometimes the metric history is not purged

---

pkg/balance/router/router_score_test.go
pkg/sqlreplay/capture/capture_test.go

Issue Number: close #649 
If the machine is slow enough, the actual value exceeds the threshold.
- Adjust the threshold of `TestControlSpeed ` and add more logs.
- Check the file prefix of `TestFileRotation` and add more logs.
Tests 
```release-note
None
```

router: fix unstable test `TestControlSpeed`

---

pkg/sqlreplay/replay/conn.go
pkg/sqlreplay/replay/conn_test.go
pkg/sqlreplay/replay/exception.go
pkg/sqlreplay/replay/mock_test.go
pkg/sqlreplay/replay/packetio.go
pkg/sqlreplay/replay/packetio_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go

Issue Number: close #654 
Create a connection when a new connection ID appears and close the connection when there's an unexpected exception.
- `replay.executeCmd` creates a connection when a new connection ID appears and closes the connection when there's a critical error
- `conn` creates a `BackendConnManager` and passes data between `replay` and `packetIO`
- `packetIO` is a fake client IO, it puts written data into a channel and reads data from a channel
Tests 
```release-note
None
```

replay: manage connections in traffic replay

---

pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/capture/mock_test.go
pkg/sqlreplay/cmd/cmd.go
pkg/sqlreplay/cmd/mock_test.go
pkg/sqlreplay/store/const.go
pkg/sqlreplay/store/loader.go
pkg/sqlreplay/store/loader_test.go
pkg/sqlreplay/store/writer.go
pkg/sqlreplay/store/writer_test.go

Issue Number: close #657 
Support loading and parsing traffic files.
- Add `loader` to read traffic files
- Separate `load.writer` from `capture.capture` to write traffic files
- Output the filename and line index when parsing `Command` fails
- Update the configuration `output` from a filename to a directory
Tests 
```release-note
None
```

store, capture: load and parse traffic files

---

pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/cmd/cmd.go
pkg/sqlreplay/cmd/mock_test.go
pkg/sqlreplay/replay/conn.go
pkg/sqlreplay/replay/conn_test.go
pkg/sqlreplay/replay/exception.go
pkg/sqlreplay/replay/mock_test.go
pkg/sqlreplay/replay/packetio.go
pkg/sqlreplay/replay/packetio_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/store/loader.go
pkg/sqlreplay/store/loader_test.go

Issue Number: close #659 
Replay commands at a customized speed.
- Replay commands with `ReplayConfig.Speed` and report errors with `failException`.
- Fix that the files are not closed in `loader`.
- Remove the codes in `packetIO` because it's unnecessary.
- Make `Command.Payload` contain the command type so that it can be used directly in replay.
- Clear the closed connection through `closeCh`.
Tests 
```release-note
None
```

replay, capture: replay commands at a customized speed

---

lib/cli/util.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/api/backend.go
pkg/server/api/backend_test.go
pkg/server/api/config.go
pkg/server/api/config_test.go
pkg/server/api/debug.go
pkg/server/api/debug_test.go
pkg/server/api/metrics_test.go
pkg/server/api/namespace.go
pkg/server/api/namespace_test.go
pkg/server/api/server.go
pkg/server/api/server_test.go
pkg/server/api/traffic.go
pkg/server/api/traffic_test.go
pkg/server/server.go

Issue Number: close #667 
add http api for capturing and replaying traffic
- Add http api for capturing and replaying traffic
- Create `JobManager` in `Server`
Tests 
```release-note
None
```

api, server: add http api for capturing and replaying traffic

---

lib/cli/main.go
lib/cli/traffic.go
lib/cli/util.go

Issue Number: close #669 
Support tiproxyctl to capture, replay, and cancel traffic jobs
- Add sub commands on tiproxyctl
Tests 
run `tiproxyctl traffic capture`, `tiproxyctl traffic replay`, `tiproxyctl traffic cancel`, and `tiproxyctl traffic show`.
```release-note
None
```

cli: add traffic commands for tiproxyctl

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/client/client_conn.go
pkg/proxy/net/packetio.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/cmd/cmd.go
pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go
pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/manager/mock_test.go
pkg/sqlreplay/replay/handshake_handler.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/report/tables.go

Issue Number: ref #642
There are some bugs when I manually test traffic capture and replay.
- Fix some bugs to make it runnable
- Refine logs for troubleshoot 
Tests 
```release-note
None
```

sqlreplay, backend: fix bugs to make traffic replay runnable

---

pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/report/report_db.go
pkg/sqlreplay/report/tables.go
pkg/sqlreplay/store/meta.go
pkg/sqlreplay/store/meta_test.go

Issue Number: close #672 
To output the progress of replay, replay needs to know the total duration or commands.
- `capture` writes duration and command count to `meta`
- `replay` reads the duration and command count to know the progress
Tests 
```release-note
None
```

sqlreplay: write meta to the output directory

---

go.mod
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/capture/mock_test.go
pkg/sqlreplay/manager/mock_test.go

Issue Number: close #674 
For existing connections, the session states are not replayed.
- Output `SET SESSION_STATES` to traffic files for existing connections.
- Output `USE db` to traffic files for new connections.
Tests 
```release-note
None
```

capture, backend: output session states to traffic files

---

pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go
pkg/proxy/backend/mock_proxy_test.go
pkg/proxy/net/command.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/cmd/cmd.go

Issue Number: close #676
Some clients are disconnected unexpectedly, the QUIT commands should still be outputted to traffic files.
- Call `Capture` when `BackendConnManager` closes
- `Capture` handles duplicated `QUIT` commands
Tests 
```release-note
None
```

backend, capture: write quit command to traffic files

---

pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go
pkg/proxy/net/protocol.go
pkg/sqlreplay/cmd/cmd.go
pkg/sqlreplay/cmd/cmd_test.go
pkg/sqlreplay/conn/backend_conn.go
pkg/sqlreplay/conn/backend_conn_test.go
pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/conn/conn_test.go
pkg/sqlreplay/conn/exception.go
pkg/sqlreplay/conn/exception_test.go
pkg/sqlreplay/conn/mock_test.go
pkg/sqlreplay/conn/prepared_stmt.go
pkg/sqlreplay/report/mock_test.go

Issue Number: close #678
When replaying `ComStmtExecute` fails, thes text and args can not be reported.
- Maintain a mapping of prepared statement ID and text+paramNum in `backendConn`
- When `ComStmtExecute` fails, query the text and parse the args in the request
Tests 
```release-note
None
```

sqlreplay, net: maintain the mapping of prepared statement ID and text

---

pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/capture/filter.go
pkg/sqlreplay/capture/filter_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/util/lex/lex.go
pkg/util/lex/lex_test.go

Issue Number: close #681
Some commands contain passwords or object storage URI, do not capture them.
- Add a simple `Lexer` to parse keywords.
- Do not capture some specific queries or commands.
Tests 
```release-note
None
```

capture: do not capture sensitive commands

---

pkg/sqlreplay/conn/exception.go
pkg/sqlreplay/conn/exception_test.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/report/report_db.go
pkg/sqlreplay/report/report_db_test.go
pkg/sqlreplay/report/report_test.go

Issue Number: close #683
Output capture time and replay time to the report table `fail`.
Output capture time and replay time to the report table `fail`.
Tests 
```
mysql> select * from fail;
+----------+------------------------------------------------------------------+-------------+---------------------------------------------------------+----------------+---------------------+---------------------+-------+
| cmd_type | digest                                                           | sample_stmt | sample_err_msg                                          | sample_conn_id | sample_capture_time | sample_replay_time  | count |
+----------+------------------------------------------------------------------+-------------+----------------------- …
```

report, conn: output capture time and replay time to the report

---

pkg/proxy/backend/mock_proxy_test.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go
pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/manager/mock_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go

Issue Number: close #685
Users may want to check the history of traffic jobs.
- Add more fields to the jobs.
- Marshal the jobs and return the string.
Tests 
```release-note
None
```

manager, replay: show the history of traffic jobs

---

pkg/manager/id/manager.go
pkg/manager/id/manager_test.go
pkg/proxy/proxy.go
pkg/proxy/proxy_test.go
pkg/server/server.go
pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/conn/conn_test.go
pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go

Issue Number: close #687 
SQL server and replayer allocate backend ID concurrently, but the ID can't overlap.
- Create a `IDManager`
- SQLServer and Replay allocate ID from IDManager
Tests 
```release-note
None
```

id, replay: add id allocator for SQL server and replayer

---

cmd/tiproxy/main.go
pkg/manager/config/config.go
pkg/manager/config/config_test.go
pkg/manager/config/manager.go
pkg/manager/config/manager_test.go
pkg/manager/config/namespace_test.go
pkg/sctx/context.go
pkg/server/api/server_test.go
pkg/server/server.go
pkg/server/server_test.go

Issue Number: close #690
When `--advertise-addr` is set, the whole `proxy` is overwritten by `toml.Unmarshal(e.overlay, base)`, which results in all the fields are empty except for `advertise-addr`.
- Remove `Sctx.Overlay` and add `Sctx.AdvertiseAddr`
- Only set `advertiseAddr` explicitly in `ConfigManager`
Tests 
1. Set the `graceful-wait-before-shutdown` in the config file
2. Start TiProxy with `--advertise-addr`
3. Start TiProxy and check the log, the config shows `graceful-wait-before-shutdown` correctly
```release-note
- Fix that the `proxy` …
```

config, cmd: fix that the proxy configs are overwritten

---

pkg/balance/router/router.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go
pkg/balance/router/router_static.go
pkg/manager/namespace/manager.go
pkg/manager/namespace/manager_test.go
pkg/proxy/backend/handshake_handler.go
pkg/server/api/debug.go
pkg/server/api/debug_test.go
pkg/server/api/mock_test.go
pkg/server/api/namespace_test.go
pkg/server/api/server.go
pkg/server/api/server_test.go
pkg/server/server.go

Issue Number: close #689 
When TiProxy starts, it may take some time to connect to PD and update the backend status. During this phase, no connections should be routed to this instance. So the HTTP API `/api/debug/health` should report an error when there's no available backends.
- Add an interface `NamespaceManager` and test `/api/debug/health` with a mocked one.
- `NamespaceManager.Ready()` returns true only when all the routers have at least one healthy backend.
- `/api/debug/health` returns OK only when `NamespaceManager.Ready()` and the server is not closing.
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write …

Make /api/debug/health return error when no backends are available

---

pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go

Issue Number: close #693 
The job history length is unlimited, which may consume much memory if the proxy runs for years.
Set the length limit to 10.
Tests 
```release-note
None
```

manager: add a limit to the capture and replay job history

---

pkg/balance/router/mock_test.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/backend/backend_conn_mgr_test.go

Issue Number: close #663 
If a redirection happens when the connection is about to close, the connScore may be incorrectly set. The source backend may have a negative connScore and the target backend has an unexpectedly higher score. The target backend will never be removed.
- Notify the router even when a connection is closing
- The router doesn't update the score if the connection refuses to redirect
Tests 
```release-note
- Fix that an unhealthy backend may be never removed
```

router, backend: fix that an unhealthy backend may be never removed

---

.golangci.yaml
Makefile
go.mod
pkg/manager/vip/network_test.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/net/capability.go
pkg/proxy/net/mysql.go
pkg/proxy/net/mysql_test.go
pkg/proxy/net/protocol.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/cmd/cmd_test.go
pkg/sqlreplay/conn/backend_conn.go
pkg/sqlreplay/conn/backend_conn_test.go
pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/conn/conn_test.go
pkg/sqlreplay/conn/exception.go
pkg/sqlreplay/conn/exception_test.go
pkg/sqlreplay/conn/mock_test.go
pkg/sqlreplay/conn/prepared_stmt.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/report/mock_test.go
pkg/sqlreplay/report/report.go
pkg/sqlreplay/report/report_db.go
pkg/sqlreplay/report/report_db_test.go
pkg/sqlreplay/report/report_test.go
pkg/sqlreplay/store/loader.go
pkg/sqlreplay/store/loader_test.go

Issue Number: ref #642 
- Reading data from gzip files fails because the reader is overwritten
- fd number is not recovered after replay because backend connections are not closed
- Paring ComPrepareStmt fails because the buffer is reset before fetching the data
- The connections are not closed immediately because the ComQuit is not checked
- The progress is wrong at the second replay because the replayedCmds is not reset
- Prepared statements are not found because unmarshaling session states fails
- Execution errors in the last 5 seconds may be not flushed
- The parsed param num in session states is wrong
- Paring ComExecuteStmt request is wrong
- `sample_replay_time` in `other_errors` is NULL
Fix all the above bugs
Enhancements:
- …

*: fix several bugs of traffic replay

---

docker/Dockerfile
pkg/metrics/metrics.go
pkg/metrics/replay.go
pkg/proxy/backend/mock_proxy_test.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/cmd/cmd.go
pkg/sqlreplay/cmd/mock_test.go
pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/conn/conn_test.go
pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go
pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/manager/mock_test.go
pkg/sqlreplay/replay/mock_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/report/report_db.go
pkg/sqlreplay/store/loader.go
pkg/sqlreplay/store/meta.go

Issue Number: close #700
- Sometimes the last commands are not replayed because the connections quit before they have finished
- There are deadlocks when the command buffer of one connection is full because it's waiting for a lock while other connections wait for decoding
- Do not cancel the context when the commands are decoded, just close the command channel
- Replace the channel with glist to make the buffer size big enough
- Slow down decoding if there are too many pending commands and abort the replay when the commands still increase
- Add metrics to monitor the pending commands and wait time
- Do not judge the job status by the progress because the progress may be incorrect
Tests 
Test: test with TPCC and check the replayed command …

replay: slow down decoding when there are too many pending commands

---

pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/manager/mock_test.go

Issue Number: close #710 
Even if the last replay is finished, the next replay may fail to start because the progress is not 100%.
Check the field `done` instead of `progress`.
Tests 
```release-note
- Fix that traffic replay may incorrectly report another job is running
```

sqlreplay: fix job running status

---

pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/store/meta.go
pkg/sqlreplay/store/meta_test.go

Issue Number: close #716 
Writing `meta` may overwrite a system file with the same name, which can be used by attackers, so a precheck is needed before capturing.
Precheck the file `meta` before traffic capture. If the file exists, quit.
Tests 
```release-note
- Do not start traffic capture if the file meta exists
```

sqlreplay: do not write traffic files if meta exists

---

pkg/server/api/server_test.go
pkg/server/api/traffic.go
pkg/server/api/traffic_test.go
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/capture_test.go
pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go
pkg/sqlreplay/manager/manager.go
pkg/sqlreplay/manager/manager_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/report/mock_test.go
pkg/sqlreplay/report/report.go
pkg/sqlreplay/report/report_db.go
pkg/sqlreplay/report/report_db_test.go
pkg/sqlreplay/report/tables.go

Issue Number: close #723
If a user executes the SQL `TRAFFIC CAPTURE` or `TRAFFIC REPLAY` on TiDB, TiDB needs to query the job status from TiProxy instances. However, the jobs are executed independently on each TiProxy, so the job should have an ID to be queried.
- Add `start-time` to the capture and replay API so that the `start-time` can be specified by TiDB as the job ID
- Add a column `replay_start_time` to the report tables so that the reports of all jobs can coexist
- Check the report table definitions to ensure the tables are well-defined
Tests 
```shell
curl -X POST "localhost:3080/api/traffic/capture" -d "duration=1m&output=/tmp/traffic&start-time=2024-12-11T12:23:00Z"
capture started%
curl -X POST …
```

sqlreplay, api: add job start time to the report and API parameters

---

go.mod
pkg/sqlreplay/capture/capture.go
pkg/sqlreplay/capture/mock_test.go
pkg/sqlreplay/store/compress.go
pkg/sqlreplay/store/compress_test.go
pkg/sqlreplay/store/const.go
pkg/sqlreplay/store/encrypt.go
pkg/sqlreplay/store/encrypt_test.go
pkg/sqlreplay/store/line.go
pkg/sqlreplay/store/line_test.go
pkg/sqlreplay/store/rotate.go
pkg/sqlreplay/store/rotate_test.go

Issue Number: close #726 
- `lumberjack` is used to write traffic commands, but it requires that each write should be less than the file size (300MB)
- `lumberjack` writes, rotates, and compresses internally, so it's hard to use S3
- Replace `lumberjack` with customized writers.
- Change the call chain from `encryptWriter -> rotateWriter` to `rotateWriter -> compressWriter -> encryptWriter`.
- Change the file name from pattern `traffic-{time}.log` to `traffic-{idx}.log`.
Tests 
```release-note
None
```

sqlreplay: remove lumberjack to support large commands

---

pkg/sqlreplay/manager/job.go
pkg/sqlreplay/manager/job_test.go

Issue Number: close #742
S3 secrets should be redacted for log and API output.
Redact the URL when marshaling the job.
Tests 
```release-note
None
```

sqlreplay: redact the S3 secrets

---

pkg/sqlreplay/store/encrypt.go
pkg/sqlreplay/store/rotate.go
pkg/sqlreplay/store/rotate_test.go

Issue Number: close #746
- Replay traffic from S3 always reports `request is canceled` because the context is passed from `storage.Open()` to `storage.Read()`
- Replay always reads only one file when the files are encrypted because `rotateReader` uses `err != io.EOF` while the `encryptReader` returns a wrapped `io.EOF`
- Do not pass a context with timeout into `storage.Open()`
- Replace `err != io.EOF` with `!errors.Is(err, io.EOF)`
Tests 
Manually test traffic replay from S3
```release-note
None
```

sqlreplay: fix replay traffic from S3 always reports request is canceled

---

pkg/server/api/server.go

Issue Number: close #752
The status is fetched before the handler is called, so the status is always 200.
Fetch the status after the handler is called. Besides, remove `path` and `end` because they can be inferred from somewhere else.
Tests 
```
[2025/03/06 10:18:57.550 +08:00] [DEBUG] [main.api] [api/server.go:166] [/api/traffic/capture]  [status=500] [method=POST] [query=] [ip=127.0.0.1] [user-agent=Go-http-client/1.1] [latency=187.75µs]
```
```release-note
- Fix wrong status in the API debug log
```

api: fix wrong status in the API debug log

---

pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/store/encrypt.go

Issue Number: close #754 
The replayer doesn't correctly set the encryption key
Set `replay.cfg.encryptionKey` instead of `cfg.encryptionKey`
Tests 
Repeat the issue steps and replay succeeds
```release-note
None
```

sqlreplay: fix replay reports invalid encryption key length

---

pkg/proxy/backend/cmd_processor_exec.go
pkg/proxy/backend/cmd_processor_test.go
pkg/util/lex/filter.go
pkg/util/lex/filter_test.go

Issue Number: close #732 
During session migration, TiProxy may need to parse a statement to see if it's a BEGIN statement. It's too heavy to use the TiDB parser because it parses the whole statement. We can just parse the first 2 tokens to see if it's BEGIN.
- Use `lex.IsStartTxn` to check if it's a start transaction statement
Tests 
```release-note
None
```

backend, lex: use a simpler lexer to parse begin statements

---

pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go

Issue Number: close #789
- When updating BackendMetricGauge, the sample is nil and TiProxy panics
- BackendMetricGauge misses memory metric
- Check sample before updating the metric
- Add memory usage to BackendMetricGauge
Tests 
```release-note
None
```

balance: fix panic in updating metrics

---

pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/factor/factor_memory_test.go
pkg/balance/factor/factor_status.go
pkg/balance/factor/factor_status_test.go

Issue Number: close #792 
When TiDB shuts down and new connections come in, the balance speed will be calculated each time because the balance speed is not preserved when the backend is missing.
For status, health, memory, and CPU factors, preserve the backend snapshot even when the backend is missing in updating scores.
Tests 
1. Create a workload to create both long and short connections
2. Scale in TiDB
3. The connections should be reserved and only one `update status risk` is printed
```release-note
None
```

balance: fix connection migration may be slower and slower when TiDB shuts down

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go
pkg/balance/factor/factor_memory.go

Issue Number: close #794
The rebalance algorithm only compares the busiest and idlest backends, but does not compare other backends. When one TiDB is unhealthy and is thought to be busiest, the second busiest will never be considered.
Sort the backends and iterate over all the backends until an unbalance is found.
Note that the routing algorithm still has a problem. It compares other backends with only the idlest one but ignores the unbalance among the busiest and the second idlest backend. For example, all the backends may be routed to, while the third one is better not.
1. CPU=0, location=1
2. CPU=1, location=0
3. CPU=1, location=1
Tests  …

balance: fix connection migration may stop when one TiDB is unhealthy

---

pkg/balance/factor/factor_conn.go
pkg/balance/factor/factor_conn_test.go

Issue Number: close #801
When I start a workload with 1000 short connections per second on a 2 TiProxy + 3 TiDB cluster, the migrations are about 120 per minute, which is the upper limit of the speed, considering that the speed is limited to 1 per second on each TiProxy.
Actually, it's useless because the CPU-based factor can do the rebalance. Connection-count-based factor should be used only when CPU usage doesn't work.
The speed of connection-count-based migration should be based on the current connection count difference, not a constant.
Tests 
Start the workload above, and the migration OPM is reduced to 8.
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/r …

Reduce useless migrations based on connection count in short connection workload

---

pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_label.go
pkg/balance/factor/factor_label_test.go
pkg/balance/observer/backend_health.go
pkg/balance/observer/backend_health_test.go
pkg/balance/observer/backend_observer.go
pkg/balance/router/router.go
pkg/balance/router/router_score.go

Issue Number: close #819
When there's only one backend and it has a different label with TiProxy, the backend should not be routed to.
- Don't skip setting the label score when there's only one backend
- Add debug logs about labels
Tests 
Steps to test debug logs:
1. Start a cluster.
2. Set labels to TiProxy and TiDB.
3. Check the debug logs.
```release-note
None
```

factor, router: routing fails when there's only one backend with a different label

---

pkg/balance/factor/factor.go
pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_balance_test.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_memory.go

Issue Number: close #822
The previous PR https://github.com/pingcap/tiproxy/pull/823 doesn't really fix the issue when the CPU scores are the same.
- Check whether the factor rejects rebalance when the scores are the same.
- Append the logs fields of all factors.
Tests 
The steps are the same as the issue.
```release-note
None
```

balance: fix connection is repeatedly migrated by CPU and location

---

conf/proxy.toml
pkg/balance/factor/factor_balance.go
pkg/balance/factor/factor_cpu.go
pkg/balance/factor/factor_health.go
pkg/balance/factor/factor_health_test.go
pkg/balance/factor/factor_memory.go
pkg/balance/metricsreader/metrics_reader.go
pkg/balance/router/router_score.go

Issue Number: close #828
- When TiDB executes heavy DML, there may be many regionMiss, which causes TiProxy to incorrectly take TiDB as unhealthy.
- When connections are migrated to one TiDB, the QPS is higher and has more backoff. Judging by the backoff number is unfair.
- There may be panic when TiDB locations are the same.
- If the router panics, the panic reason is not logged.
- Remove regionMiss backoffs in the health judgment
- Change backoff number to backoff rate in the health judgment
- Fix possible panic
- Recover router panic and log the panic stack
Tests 
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-notes-style-guide.html) to write a …

balance: fix TiDB regionMiss backoff causes TiProxy to incorrectly migrate connections

---

lib/config/balance.go
pkg/balance/router/backend_selector.go
pkg/balance/router/group.go
pkg/balance/router/group_test.go
pkg/balance/router/router.go
pkg/balance/router/router_score.go
pkg/balance/router/router_score_test.go
pkg/balance/router/router_static.go
pkg/proxy/backend/backend_conn_mgr.go
pkg/proxy/net/packetio.go
pkg/proxy/net/proxy.go
pkg/proxy/net/proxy_test.go
pkg/sqlreplay/conn/packetio.go

Issue Number: close #849 
The previous PR supports CIDR but doesn't pass the client IP in.
- Pass the client IP and proxy IP into the router
- The routing-rule is changed to `client_cidr` and `proxy_cidr`
Tests 
E2E tests are added to endless.
```release-note
None
```

router: pass the client IP to the router to route based on CIDR

---

pkg/manager/meter/meter.go
pkg/manager/meter/meter_test.go

Issue Number: ref #857
The written metering data may contain empty clusters.
Fix wrong array initialization.
Tests 
```release-note
None
```

meter: fix meter data may contain empty data

---

pkg/sqlreplay/cmd/audit_log_plugin.go
pkg/sqlreplay/cmd/audit_log_plugin_test.go
pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/replay/mock_test.go
pkg/sqlreplay/replay/replay.go

Issue Number: close #862
- Audit logs record the beginning and end of each statement, but we only care about the beginning
- Audit logs may contain existing connections, wait until the current db is specified
- Move the deduplication from the replay process to the decode process to decouple logic
- If a connection is not started with a `Connected` event, ignore the table accesses until a `Use` statement shows
Tests 
```release-note
None
```

sqlreplay: deduplicate audit logs and ignore uninitialized statements

---

pkg/sqlreplay/replay/replay.go

Issue Number: close #880
The replay failure may not be written to the table `fail`.
Close `report` before closing `replay`.
Tests 
Replay and check the `tiproxy_traffic_replay.fail`.
```release-note
None
```

replay: fix report may not be written before close

---

pkg/sqlreplay/replay/merge_decoder.go
pkg/sqlreplay/replay/merge_decoder_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go

Issue Number: close #875 
1. Add a `mergeDecoder` struct to merge sort the result of decoders. However, in the current implementation, the commands returned by each internal decoder are not sorted by the `StartTs`, so the order of `mergeDecoder` is also not strictly guaranteed.
2. Support to add multiple `Input`, split by `,`.
Tests 
Save the same audit file to `/tmp/audit-1/xxx` and `/tmp/audit-2/xxx`. Replay with `./replayer --command-start-time 2025-09-14T13:53:58+08:00 --format audit_log_plugin --log-file ./replay.log --input /tmp/audit-1,/tmp/audit-2`, and the same query will be executed two times.
Please refer to [Release Notes Language Style Guide](https://pingcap.github.io/tidb-dev-guide/contribute-to-tidb/release-n …

replay: implement reading commands from multiple sources

---

cmd/replayer/main.go

Issue Number: close #876 
We can only stop the replayer by `kill -9`. It's better to break for `Ctrl+C`.
Stop the replayer when received SIGINT.
Tests 
```release-note
None
```

cmd: break the replayer when received signals

---

cmd/replayer/main.go
lib/cli/traffic.go
pkg/server/api/traffic.go
pkg/sqlreplay/replay/mock_test.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go

Issue Number: close #889 
Ignore decode errors so that it's more robust.
Tests 
```release-note
None
```

replay, cmd: support ignoring errors in replay

---

pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/replay/replay.go
pkg/sqlreplay/replay/replay_test.go
pkg/sqlreplay/store/rotate.go

Issue Number: close #904 
In the client mode, no metrics are available so we can only add logs
- Report the status every 10s
- Add the log file directory
Tests 
```
[2025/09/16 19:09:10.225 +08:00] [INFO] [main.replay.replay] [replay/replay.go:453] [replay progress]  [replayed_cmds=273803] [pending_cmds=201777] [filtered_cmds=0] [decoded_cmds=475580] [total_wait_time=25.658075998s] [replay_elapsed=30.017181333s] [decode_elapsed=29.529031292s]
[2025/09/16 19:09:10.247 +08:00] [INFO] [main.replay.replay.loader] [store/rotate.go:222] [reading next file]  [prefix=file:///Users/zhangming/Downloads/audit] [file=tidb-audit-2025-09-14T19-11-18.766.log]
``` …

sqlreplay: add logs for replay progress

---

pkg/balance/router/router.go
pkg/balance/router/router_test.go

Issue Number: close #909 
The cluster id in metering data should be keyspace but is zone
Fix the label key
Tests 
```release-note
None
```

router: fix the cluster_id is wrong in the metering data

---

pkg/sqlreplay/store/rotate.go
pkg/sqlreplay/store/rotate_test.go

Issue Number: close #908
The `marker` doesn't have prefix after the first iteration.
Add path prefix for them.
Tests 
```release-note
None
```

store: fix the issue that marker doesn't have path prefix

---

pkg/sqlreplay/conn/conn.go
pkg/sqlreplay/replay/replay.go

Issue Number: close #904
Add more logs so we can know the bottleneck.
Added more log fields
Tests 
```
[2025/09/17 16:11:40.305 +08:00] [INFO] [main.replay.replay] [replay/replay.go:476] [replay progress]  [replayed_cmds=423974] [pending_cmds=55260] [filtered_cmds=0] [decoded_cmds=479234] [total_wait_time=27.045359264s] [extra_wait_time=0s] [replay_elapsed=50.041051125s] [decode_elapsed=29.763948709s]
[2025/09/17 16:11:46.898 +08:00] [INFO] [main.replay.replay] [replay/replay.go:533] [replay finished]  [start_time=2025-09-17 16:10:50.264865 +0800 CST] [end_time=2025-09-17 16:11:46.898992 +0800 CST] [command_start_time=2025-09-14 19:10:49 +0800 CST] [format=audit_log_plugin] [username=root] [ignore_errs=false] [speed=1] [read_only=false] …
```

replay: add more fields to replay logs

---

pkg/sqlreplay/store/rotate.go
pkg/sqlreplay/store/rotate_test.go

Issue Number: close #917
Add a cache for the S3 file lists.
Tests 
```release-note
None
```

store: add cache for file name and size
